### ISSUE TITLE
Build error: Property '_cssClass' is private and only accessible within class 'IonicSelectableComponent'.

### ISSUE THREAD

**Issue by namgiang** [eakoriakin/ionic-selectable#101]
Hi, I have a build error (I'm using @ionic/angular@4.0.0-beta.12, and ionic-selectable@4.0.0). I'm using lazy loading and everything is configured correctly.

`BUILD ERROR
**/settings.component.ts.SettingsComponent.html(65,21): Directive IonicSelectableComponent, Property '_cssClass' is private and only accessible within class 'IonicSelectableComponent'.`

`**/settings.component.ts.SettingsComponent.html: Directive IonicSelectableComponent, Property '_isMultipleCssClass' is private and only accessible within class 'IonicSelectableComponent'.`

`**/settings.component.ts.SettingsComponent.html: Directive IonicSelectableComponent, Property '_hasValueCssClass' is private and only accessible within class 'IonicSelectableComponent'.`

`**/settings.component.ts.SettingsComponent.html: Directive IonicSelectableComponent, Property '_hasPlaceholderCssClass' is private and only accessible within class 'IonicSelectableComponent'.
`

Could you please check? Thanks.

**Comment by eakoriakin** [comment]
Hi, try the latest `4.1.3` version.

```
npm install ionic-selectable@4.1.3
```

**Comment by blendmaker** [comment]
I am running into the same issue with ionic-selectable@4.4.1 . I am using it in a component library and i get those errors while compiling.

**Comment by niczm25** [comment]
When i typed and run `ionic cordova build android --prod`, i will get the same error above.
