### ISSUE TITLE
(blur) is deprecated in ion-input, use (ionBlur) instead

### ISSUE THREAD

**Issue by JJPell** [eakoriakin/ionic-selectable#103]
Just so you know I am getting this console warning on pages that I'm using the select-searchable component. Not sure if his may become an issue in the future.

`(blur) is deprecated in ion-input, use (ionBlur) instead`

**Comment by eakoriakin** [comment]
Hey, thanks for letting me know, I’ll fix it

**Comment by eakoriakin** [comment]
Fixed in 3.1.0 and 4.1.3.
