### ISSUE TITLE
Enable Pro Features for old Versions

### ISSUE THREAD

**Issue by JacksonWolff** [eakoriakin/ionic-selectable#105]
How can I get PRO features working on release 3.0.3? 
(At latest version, you released for everyone).
Thanks for the good work!

**Comment by eakoriakin** [comment]
Hey, for now Pro features are only available in v4, but I’m working on adding them to v3. It’ll take a couple of days.

**Comment by JacksonWolff** [comment]
Thanks for the update. Let me know if I can help you.

Cheers!

**Comment by eakoriakin** [comment]
You can get it for any price you wish from https://gumroad.com/l/nkUr, while I'm making it open source.

**Comment by eakoriakin** [comment]
Ionic Selectable Pro is now available for free.

**Ionic 3**
```
npm install ionic-selectable@3.1.0
```

**Ionic 4**
```
npm install ionic-selectable@4.1.3
```
