### ISSUE TITLE
Style difference from Ionic Select

### ISSUE THREAD

**Issue by shdehnavi** [eakoriakin/ionic-selectable#106]
hi
i want to select-searchable style be same as ion-select style like as below image:
<img width="282" alt="aa" src="https://user-images.githubusercontent.com/6625055/47414757-a0e4cb00-d77e-11e8-88d6-dce5520de1c5.png">

item one and item three is ion-select and item two is select-searchable component
item two must be same as item one and item three's ui

what's the solution>

**Comment by eakoriakin** [comment]
Hi, can you share your code and `ionic-selectable` version that you use?

**Comment by eakoriakin** [comment]
Closed for inactivity.
