### ISSUE TITLE
Unable to change title

### ISSUE THREAD

**Issue by Penteas** [eakoriakin/ionic-selectable#107]
I'm trying to use the Title template example, but I'm not able to put it working.

Showing the piece of code:
```
<ion-col col-2 align-self-end>
   <button ion-button icon-only clear class="botaopesquisar">
        <ionic-selectable #searchservicos item-content [(ngModel)]="codservico" 
              [ngModelOptions]="{standalone: true}" [hasVirtualScroll]="true" [items]="servicos" 
              itemValueField="chave_cuorg" [searchFailText]="'Não foram encontrados serviços.'" 
              itemTextField="desig_cuorg" [canSearch]="true" [isMultiple]="true" 
              (onChange)="linkServico($event)">
      <ng-template ionicSelectableTitleTemplate>
              Test Title
      </ng-template>
   </ionic-selectable>
 </button>
</ion-col>
```

I tried to use exactly the same configurations that the example has, but still without success. Can anyone help me?

**Comment by eakoriakin** [comment]
Hey, templates used to be a part of paid functionality that I haven't yet included in `npm` package.

But you can get it `v3` with all features for 0 price from https://gumroad.com/l/nkUr for now.
Check out README inside the archive on how to install it.

**Comment by dbroeglin** [comment]
Thanks a lot for open sourcing the feature! You did great work with ionic-selectable! Kudos!

I lost a few hours trying to get templates working with version 3.0.3. Maybe if you do not have the time to include it in the npm package, you could just quickly add a warning to the github README ? Just to warn other people that would want to use templates.

**Comment by eakoriakin** [comment]
Hi, Ionic Selectable Pro is now available for free.

**Ionic 3**
```
npm install ionic-selectable@3.1.0
```

**Ionic 4**
```
npm install ionic-selectable@4.1.3
```
