### ISSUE TITLE
Select All Feature when [isMultiple] is true

### ISSUE THREAD

**Issue by mayoljonathan** [eakoriakin/ionic-selectable#110]
Hi there, thanks for this awesome plugin. It would be good if there is a select all/unselect all feature when selecting multiple items or an event emitted when the user selects an item.

**Comment by rupendraa** [comment]
same req. here

**Comment by eakoriakin** [comment]
Hey guys, where would you add these Select and Unselect buttons? I thought in the footer, but wouldn't the footer become too crowded. Any ideas on design?

**Comment by christopheelkhoury** [comment]
I would recommend doing it at the other side of the Cancel button
A Select All button that changes to Unselect All.

**Comment by AlbertoGomezMartin** [comment]
Same request here. Would be really appreciated and useful for large options.

**Comment by christopheelkhoury** [comment]
@eakoriakin need a hand?

**Comment by eakoriakin** [comment]
Hi @christopheelkhoury, thanks a lot. I really appreciate it, but with this one I've already have an idea on how to implement.
Instead of adding additional buttons the the footer, I'll allow developers to customize buttons with a template. It'll look something like this:

```
<ionic-selectable #portComponent>
  <ng-template ionicSelectableFooterTemplate>
    <ion-toolbar>
      <ion-row>
        <ion-col [size]="4">
          <ion-button expand="full"
            (click)="portComponent.selectAllItems()">
            Select All
          </ion-button>
        </ion-col>
        <ion-col [size]="4">
          <ion-button expand="full"
            (click)="portComponent.deselectAllItems()">
            Deselect All
          </ion-button>
        </ion-col>
        <ion-col [size]="4">
          <ion-button expand="full" (click)="portComponent.confirmItems()">
            OK
          </ion-button>
        </ion-col>
      </ion-row>
    </ion-toolbar>
  </ng-template>
</ionic-selectable>
```

**Comment by eakoriakin** [comment]
Hey guys, I've just finished it 😎 enjoy!

Demo:
https://stackblitz.com/edit/ionic-selectable-footer-template?file=app/pages/home/home.html

Please note that there were some breaking changes. See release notes for more details.
- Ionic 3 [3.3.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/3.3.0)
- Ionic 4 [4.3.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/4.3.0)

**Comment by AlbertoGomezMartin** [comment]
Thank you @eakoriakin !

**Comment by jaysonyoung1** [comment]
Hey everyone, sorry to bring up an old thread, but what if we added [canSearch] = "true"? Meaning, only selecting the items that remained after filtering.
