### ISSUE TITLE
How to set the default value to search

### ISSUE THREAD

**Issue by faisshai** [eakoriakin/ionic-selectable#111]

**Comment by mikaelboff** [comment]
You can't set it, the property is just read-only

**Comment by eakoriakin** [comment]
Hey guys, it's now possible to set `searchText` in both [3.2.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/3.2.0) and [4.2.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/4.2.0) versions.

```
@ViewChild('portComponent') portComponent: IonicSelectableComponent;
...
this.portComponent.searchText = 'En';
```
