### ISSUE TITLE
Is there a way to prevent select close on background click ?

### ISSUE THREAD

**Issue by Kaz-** [eakoriakin/ionic-selectable#113]
Hi,

I was wondering if there is any way to prevent the closing of select window when you click on the background ?

My app users have big fingers and they're getting annoyed by the window closing when they click outside of the select window by mistake :') !

Couldn't find anything about it in the docs ...

(PS : my app is running on tablets)

**Comment by eakoriakin** [comment]
Hey mate, I've added [isBackdropCloseEnabled](https://github.com/eakoriakin/ionic-selectable/wiki/Documentation#isbackdropcloseenabled) field in both [3.2.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/3.2.0) and [4.2.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/4.2.0) versions. Enjoy 😄
