### ISSUE TITLE
lazy loading usage error in ionic 3.x

### ISSUE THREAD

**Issue by shdehnavi** [eakoriakin/ionic-selectable#114]
Hi, i'm getting this error in lazy loading:

`ERROR Error: Uncaught (in promise): Error: No component factory found for SelectSearchablePageComponent. Did you add it to @NgModule.entryComponents?(…)`

here is my code:

new-avertise.module.ts:
```
import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { NewAdvertisePage } from './new-advertise';

import { IonicStepperModule } from 'ionic-stepper';
import { IonicSelectableModule } from 'ionic-selectable';

@NgModule({
  declarations: [
    NewAdvertisePage,
  ],
  imports: [
    IonicPageModule.forChild(NewAdvertisePage),
	 IonicStepperModule,
	 IonicSelectableModule
  ],
})
export class NewAdvertisePageModule {}
```

and also in `new-advertise.ts` : 

`import { IonicSelectableComponent } from 'ionic-selectable';
`

**Comment by eakoriakin** [comment]
Hi, try the latest [3.1.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/3.1.0) version.
```
npm i ionic-selectable@3.1.0
```

Then check out a live [demo on Stackblitz](https://stackblitz.com/edit/ionic-selectable-basic) to make sure your configuration is correct.
