### ISSUE TITLE
Set custom class

### ISSUE THREAD

**Issue by lgme** [eakoriakin/ionic-selectable#115]
How can you set a class on ionic-selectable? I'm thinking of something like **<ionic-selectable [selectOptions]="{ cssClass: isDark ? 'dark-theme' : 'light-theme' }"...** but it's not working.

**Comment by eakoriakin** [comment]
Hi, no need for an option, just add a class directly to `<ionic-selectable>` tag.

```
<ionic-selectable class="ionic-selectable-dark">
</ionic-selectable>
```
