### ISSUE TITLE
Property 'showAddItemTemplate' and 'hideAddItemTemplate' does not exist on type 'IonicSelectableComponent'

### ISSUE THREAD

**Issue by isyel** [eakoriakin/ionic-selectable#116]
I am trying to do a add item when search fails, but i am getting an error.. the showAddItemTemplate and hideAddItemTemplate doesn't seem to exist in my IonicSelectableComponent. 
i did my install using 
// Ionic 3
npm install ionic-selectable@3.0.3 --save
because i'm using ionic 3. what am i doing wrongly.. and why is the property not existent in the install bundle.

my ionic info is
`C:\Users\ISRAEL\IdeaProjects\TQArtisan>ionic info
√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)  : 4.0.6 (C:\Users\ISRAEL\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0

System:

   Android SDK Tools : 26.0.2
   NodeJS            : v8.9.4 (C:\Program Files\nodejs\node.exe)
   npm               : 6.1.0
   OS                : Windows 10

Environment:

   ANDROID_HOME : C:\Users\ISRAEL\AppData\Local\Android\sdk2
`

![ionic-selectable-error](https://user-images.githubusercontent.com/16913244/48727590-fe135580-ec32-11e8-9205-ef6debb1a519.PNG)

**Comment by eakoriakin** [comment]
Hi, upgrade to 3.1.0 version.
