### ISSUE TITLE
[bug] NgModel bind issue

### ISSUE THREAD

**Issue by indraraj26** [eakoriakin/ionic-selectable#119]
How do you set default value? 
its not working as it should display by default USA but its not displaying anything again i have to select

```
>  code
 <ion-item>
    <ion-label stacked class="label-color">Country</ion-label>
       <ionic-selectable item-content [(ngModel)]="test.country" name="test" [items]="testlist" itemValueField="id" itemTextField="name" 
                             [canSearch]="true" (onChange)="portChange($event)"> 
                             <ng-template ionicSelectableCloseButtonTemplate>
                                    <ion-icon name="close-circle" style="font-size: 24px;"></ion-icon>
                                 </ng-template>
                         </ionic-selectable>
                         <p> {{test?.country}}</p>
                         </ion-item>
```

> test = { country: 'USA'}

> testlist = [{id:1, name:"SPAIN"},
{id:2, name:"USA"},
{id:3, name:"INDIA"},
{id:4, name:"CHINA"},
{id:5, name:"SRI LANKA"},]

Thank you

**Comment by eakoriakin** [comment]
Hey, you `test` should contain a country object with `id`, e.g.:
```
test = { country: {id:2, name:"USA"}}
```

**Comment by indraraj26** [comment]
yes it works! Thank you for instant support :) 
Let me start applying this same method on prod code....

**Comment by eakoriakin** [comment]
You're welcome 👍, don't forget to start the project

**Comment by indraraj26** [comment]
> Hey, your `test` should contain a country object with `id`, e.g.:
> 
> ```
> test = { country: {id:2, name:"USA"}}
> ```

@eakoriakin Hey, is this possible i dont want to make new object id name, i want to pass only id test = { country: 2 } as my backend connect to web and app too they dont want to change the way.

We have been using ion-select and ion-option where we loop testlist get the id and name, pass backend to id only.

> <ion-select [(ngModel)]="test.country">
> <ion-option *ngFor="let re of testlist" [value]="re.id"> {{re.name}}</ion-option>
> </ion-select>
> 
> test = { country: 2 }
> 
> testlist = [{id:1, name:"SPAIN"},
> {id:2, name:"USA"},
> {id:3, name:"INDIA"},
> {id:4, name:"CHINA"},
> {id:5, name:"SRI LANKA"},]
> 
> 

Thank you.

**Comment by eakoriakin** [comment]
Hey, yeah it is possible with `shouldStoreItemValue` parameter as `true`.
Check out docs and demo below:
https://github.com/eakoriakin/ionic-selectable/wiki/Documentation#shouldstoreitemvalue
https://stackblitz.com/edit/ionic-selectable-should-store-item-value?file=pages%2Fhome%2Fhome.html

**Comment by indraraj26** [comment]
i applied given method to my prod code but i am getting this when i am trying to update/edit value

```
> e.html:10 ERROR TypeError: Cannot read property 'find' of undefined
>     at e._formatValueItem (ionic-selectable.min.js:1)
>     at Object.eval [as updateRenderer] (e.html:10)
>     at Object.debugUpdateRenderer [as updateRenderer] (core.js:14735)
>     at checkAndUpdateView (core.js:13849)
>     at callViewAction (core.js:14195)
>     at execEmbeddedViewsAction (core.js:14153)
>     at checkAndUpdateView (core.js:13845)
>     at callViewAction (core.js:14195)
>     at execEmbeddedViewsAction (core.js:14153)
>     at checkAndUpdateView (core.js:13845)
```

**Comment by eakoriakin** [comment]
Could you give me more info? I cannot tell much from the error above...

**Comment by indraraj26** [comment]
this is what i have used
This country ion-item is in template driven form i am able to save but when i am trying to update/edit i.e update the same form get the country id to display
When i am opening the form to edit that i am getting **above error**
I am getting countryList from API in ionViewDidLoad 

>  <ion-item>
                                    <ion-label stacked class="label-color">Country</ion-label>
           <ionic-selectable item-content [(ngModel)]="manageContact.country" name="test" [items]="countryList" itemValueField="id" itemTextField="name" 
                                 [canSearch]="true"  [shouldStoreItemValue]="true"> 
                                 <ng-template ionicSelectableCloseButtonTemplate>
                                        <ion-icon name="close-circle" style="font-size: 24px;" color="primary"></ion-icon>
                                     </ng-template>
                             </ionic-selectable>
                            </ion-item>

Ion-selectable 3.1.0

**Comment by indraraj26** [comment]
Dear @eakoriakin, 
Will you look into this issue?

**Comment by eakoriakin** [comment]
Hey, could you put this particular peace of code to `StackBlitz` or `Github`, so I could run the project and debug the error?

**Comment by indraraj26** [comment]
Dear @eakoriakin , Sorry to say that i cant reproduce this bug in newly example project but still the error persist in Production code.

Anyway i have used modal to make searchable dropdown.

Thank you for your quick response.

**Comment by shraddha-R** [comment]
Not able to store ngModel value.. It is blank 
<ionic-selectable item-content name="zone" formControlName="zone" [(ngModel)]="zone" itemValueField="address_zone_id" itemTextField="address_zone_id" [shouldStoreItemValue]="true" [items]="zoneName"[canSearch]="true" (onChange)="selectedStreet(zone)" >
</ionic-selectable>

JSON:
zoneName:[{address_zone_id: 2}]

Please help

**Comment by shraddha-R** [comment]
Hello @eakoriakin, can you please comment on the solution. Need your help, quite urgent.. thanks
