### ISSUE TITLE
ionicSelectableCloseButtonTemplate is not rendering in ionic

### ISSUE THREAD

**Issue by indraraj26** [eakoriakin/ionic-selectable#120]
```

> <ion-item>
>              <ion-label stacked class="label-color">Country</ion-label>
>                             <ionic-selectable item-content [(ngModel)]="test.country" name="test" [items]="testlist" itemValueField="id" itemTextField="name" 
>                             [canSearch]="true" (onChange)="portChange($event)"> 
>                             <ng-template ionicSelectableCloseButtonTemplate>
>                                     <ion-icon name="close-circle" style="font-size: 24px;"></ion-icon>
>                                 </ng-template>
>                         </ionic-selectable>
>                         <p> {{test?.country}}</p>
>                         </ion-item>

```
copy this url and paste in your browser
[https://i.ibb.co/1fNbk2Q/render.png](url)

Version: 

> Ionic:

   ionic (Ionic CLI)  : 4.4.0 (C:\Users\HP\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.3.0
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 14 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\HP\AppData\Local\Android\Sdk)
   NodeJS            : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

Thank you

**Comment by eakoriakin** [comment]
Which `ionic-selectable` version do you use?

**Comment by indraraj26** [comment]
> "ionic-selectable": "^3.0.3",

**Comment by eakoriakin** [comment]
Update to [3.1.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/3.1.0).

**Comment by indraraj26** [comment]
yes it works! Thank you for instant support :)

**Comment by giovannipds** [comment]
Damn it, I was hitting my head tried to get it working on the older version as well, could you please inform this template support at docs @eakoriakin? Thank you very much for everything. =} <3 I'll be implementing it now.
