### ISSUE TITLE
Ionic-selectable does not work with Ionic 4.0.0-beta.18

### ISSUE THREAD

**Issue by MartineNavara** [eakoriakin/ionic-selectable#121]
All components are now prefixed with Ion.

I'm using @ionic/angular 4.0.0-beta.18 and ionic-selectable 4.1.3

I see the following errors:
`./node_modules/ionic-selectable/esm5/ionic-selectable.min.js 1:39590-39597
"export 'Content' was not found in '@ionic/angular'
warnings @ client:154
client:154 ./node_modules/ionic-selectable/esm5/ionic-selectable.min.js 1:39707-39721
"export 'InfiniteScroll' was not found in '@ionic/angular'
warnings @ client:154
client:154 ./node_modules/ionic-selectable/esm5/ionic-selectable.min.js 1:23876-23880
"export 'Item' was not found in '@ionic/angular'`

**Comment by eakoriakin** [comment]
Hi guys, could you share a git repo or Stackblitz with the error, so I could reproduce it?

**Comment by eakoriakin** [comment]
This seems to be the same as #125. I'll have a look.

**Comment by MartineNavara** [comment]
Tried using Stackblitz, but it doesn't have access to the newest beta from Ionic.
The following document describes the breaking change (prefixed ionComponents):
https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md

**Comment by eakoriakin** [comment]
@MartineNavara, thanks

**Comment by neerajrd25** [comment]
Hi @eakoriakin  Ion has realease RC version, I hope this will make your task bit easy.

**Comment by eakoriakin** [comment]
@neerajrd25 thanks 👍

**Comment by elitacco** [comment]
I created a pulled request #127 that should fix this issue

**Comment by eakoriakin** [comment]
Hey guys, I've fixed it in [4.2.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/4.2.0) release.
