### ISSUE TITLE
build error after upgrading from Ionic 4.0.0-beta.17 to  Ionic 4.0.0-beta.19

### ISSUE THREAD

**Issue by sudhishsasi** [eakoriakin/ionic-selectable#125]
ERROR in node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable-page.component.d.ts(2,10): error TS2305: Module '"/Users/yyyy/DEV/AP/node_modules/@ionic/angular/dist/index"' has no exported member 'Content'.
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable-page.component.d.ts(2,19): error TS2305: Module '"/Users/yyyy/DEV/AP/node_modules/@ionic/angular/dist/index"' has no exported member 'InfiniteScroll'.
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts(3,10): error TS2305: Module '"/Users/yyyy/DEV/AP/node_modules/@ionic/angular/dist/index"' has no exported member 'Item'.

**Comment by eakoriakin** [comment]
Hey, which version of `ionic-selectable` do you use?

**Comment by sudhishsasi** [comment]
Latest version 4.1.3

**Comment by eakoriakin** [comment]
Hey mate, I've fixed it in [4.2.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/4.2.0) release.
