### ISSUE TITLE
Show confirmation to select one item

### ISSUE THREAD

**Issue by jdnichollsc** [eakoriakin/ionic-selectable#128]
Hi man,

Thanks for this awesome plugin! can you add the option to show the buttons to confirm an item selected? or using alerts to confirm before modify the value?

Thanks!

**Comment by eakoriakin** [comment]
Hey mate, could you describe your use case in more detail? Seems like you need some kind of validation...

Also, take a look at the already existing options:
- [itemsToConfirm](https://github.com/eakoriakin/ionic-selectable/wiki/Documentation#itemstoconfirm)
- [isOkButtonEnabled](https://github.com/eakoriakin/ionic-selectable/wiki/Documentation#isokbuttonenabled)
-[Min/max selection](https://github.com/eakoriakin/ionic-selectable/wiki/Documentation#minmax-selection)

**Comment by jdnichollsc** [comment]
Yeah, but these properties only work for multiple items

**Comment by eakoriakin** [comment]
Okay, I see... If they worked for a single selection, would that be okay for you?

**Comment by jdnichollsc** [comment]
It would be awesome!

**Comment by eakoriakin** [comment]
Hey, it's done! Enjoy 🙂 
Just install the version you need [3.2.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/3.2.0) or [4.2.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/4.2.0).

**Comment by jdnichollsc** [comment]
OMG, I owe you one! 🤙
Thanks mate for the christmas present 🙌
