### ISSUE TITLE
Custom class for modal opened by ionic-selectable

### ISSUE THREAD

**Issue by MartineNavara** [eakoriakin/ionic-selectable#132]
It's currently easy to apply some custom styles to the content of the modal, by applying those to the ionic-selectable-page. 
For our implementation I would like to apply styles to the modal containing the ionic-selectable-page without affecting all other modals in the application. This would be easier if there is added a custom class on the creation of the modal.

**Comment by eakoriakin** [comment]
Hey, it's done as a part of [3.4.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/3.4.0) and [4.4.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/4.4.0) release.
