### ISSUE TITLE
Search message

### ISSUE THREAD

**Issue by javier-gm** [eakoriakin/ionic-selectable#135]
Is it possible to customize or use a template for the search bar placeholder? Or at least change the language? I need it in spanish.

**Comment by eakoriakin** [comment]
Hi, yes, you need these options:
- [searchPlaceholder](https://github.com/eakoriakin/ionic-selectable/wiki/Documentation#searchplaceholder)
- [searchFailText](https://github.com/eakoriakin/ionic-selectable/wiki/Documentation#searchfailtext)
- [Search fail template](https://github.com/eakoriakin/ionic-selectable/wiki/Documentation#search-fail-template)
