### ISSUE TITLE
[Err]: on usage  shouldStoreItemValue

### ISSUE THREAD

**Issue by lucasprogamer** [eakoriakin/ionic-selectable#136]
when I try to use shouldStoreItemValue I get this error, otherwise I get the whole object in formcontrol
Error:
 `e.html:10 ERROR TypeError: Cannot read property 'find' of undefined
    at e._formatValueItem (ionic-selectable.min.js:1)
    at Object.eval [as updateRenderer] (e.html:10)
    at Object.debugUpdateRenderer [as updateRenderer] (core.js:14735)
    at checkAndUpdateView (core.js:13849)
    at callViewAction (core.js:14195)
    at execEmbeddedViewsAction (core.js:14153)
    at checkAndUpdateView (core.js:13845)
    at callViewAction (core.js:14195)
    at execEmbeddedViewsAction (core.js:14153)
    at checkAndUpdateView (core.js:13845)`

MyCode:

 `<ionic-selectable
			item-content
			formControlName="victim_id"
			itemValueField="id"
			shouldStoreItemValue="true"
			itemTextField="name"
			[items]="persons"
			[canSearch]="true"
			(onSearch)="searchPersons($event)">
		  </ionic-selectable>`

**Comment by eakoriakin** [comment]
Try adding square brackets to: `[shouldStoreItemValue]="true"`

**Comment by indraraj26** [comment]
same error i am getting

**Comment by eakoriakin** [comment]
Can you add a stackblitz report with this error?

**Comment by indraraj26** [comment]
@eakoriakin  I dont get any error in sample project i have just made one locally project without backend.
But the same code i moved to my production with backend i am getting the above error ?

it would be great if you can check my project through team viewer
Thank you for your awesome package

**Comment by indraraj26** [comment]
when i click to the error i am pointing to this line

> `e.prototype._formatValueItem=function(e){var t=this;if(this._shouldStoreItemValue){`

**Comment by eakoriakin** [comment]
Can you show me a sample of an array of persons that you get from the backend?

**Comment by indraraj26** [comment]
Dear @eakoriakin,

I have shared all detail in my thread.
Thank you.

**Comment by eakoriakin** [comment]
Hi @lucasprogamer I see... Sorry but I don't have time to investigate an issue in your code, unless your provide a StackBlitz repo with a reproachable error.

I'm closing it for now, feel free to reopen it anytime with a reproducible repo.

**Comment by lucasprogamer** [comment]
Ohh sorry for the late, i'm discover something, this error happenings when i start the array empty if i have any content inside then this is resolved

**Comment by lucasprogamer** [comment]
I'll provider the stacksBliz soon
