### ISSUE TITLE
required attribute not triggered

### ISSUE THREAD

**Issue by RidClick** [eakoriakin/ionic-selectable#140]
Using ngForm with ngModel and required the form is not validated, the required attribute is simply not released, can you tell me how I can get the ionic-selectable to be required?

My code

> <form #testForm="ngForm">
        <ion-item>
            <ion-label>Test required</ion-label>
            <ionic-selectable
                [(ngModel)]="test"
                name="test"
                headerColor="primary"
                [items]="items"
                itemValueField="id"
                itemTextField="name"
                [canSearch]="true" required>
                <ng-template ionicSelectableCloseButtonTemplate>
                    <ion-icon name="arrow-back" style="font-size: 24px;"></ion-icon>
                </ng-template>
            </ionic-selectable>
        </ion-item>
</form>

**Comment by eakoriakin** [comment]
I cannot check whether `required` attribute from works, but other approach using `Angular ReactiveForms` works for sure. Check it out here:

https://stackblitz.com/edit/ionic-selectable-form-control?file=pages/home/home.html
