### ISSUE TITLE
Ionic 4: No value accessor for form control with unspecified name attribute

### ISSUE THREAD

**Issue by ViVer-7** [eakoriakin/ionic-selectable#142]
Hi,
I'm using the 4.2.0 version of ionic-selectable on Ionic 4 and it seems to be working fine, but there's an error message in the log pointing to the ionic-selectable component:

> Error: No value accessor for form control with unspecified name attribute

Can't figure out what's causing this.
Any help would be appreciated...

**Comment by eakoriakin** [comment]
Hi, can you provide a code sample, and sample of items you pass to the component?

**Comment by ViVer-7** [comment]
Sorry for delay.
Here's the html code:

`        <ion-item>
          <ion-label>Team</ion-label>
          <ionic-selectable #teamComponent item-content [(ngModel)]="poule.team" [items]="teams"
            itemValueField="teamKey" itemTextField="teamName" [canSearch]="false" [hasOkButton]="true"
            [isEnabled]="categoryComponent.value" (onChange)="teamChange($event)"
            [placeholder]="categoryComponent.value ? '' : 'Choose">
          </ionic-selectable>
        </ion-item>`

**Comment by eakoriakin** [comment]
Hey, html looks good. Must be sth wrong with the configuration. Can I see your package.json?

**Comment by ViVer-7** [comment]
> {
  "name": "TestApp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^7.2.4",
    "@angular/core": "^7.2.4",
    "@angular/forms": "^7.2.4",
    "@angular/http": "^7.2.4",
    "@angular/platform-browser": "^7.2.4",
    "@angular/platform-browser-dynamic": "^7.2.4",
    "@angular/router": "^7.2.4",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/deeplinks": "^5.0.0",
    "@ionic-native/fcm": "^5.0.0",
    "@ionic-native/social-sharing": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.0.1",
    "cordova-android": "7.1.4",
    "cordova-browser": "5.0.4",
    "cordova-ios": "4.5.5",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-fcm-with-dependecy-updated": "2.4.0",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^2.3.3",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-socialsharing": "5.4.4",
    "core-js": "^2.6.4",
    "es6-promise-plugin": "4.2.2",
    "ionic-plugin-deeplinks": "1.0.17",
    "ionic-selectable": "^4.2.0",
    "moment": "^2.24.0",
    "rxjs": "~6.3.3",
    "zone.js": "~0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.12.4",
    "@angular-devkit/build-angular": "^0.12.4",
    "@angular-devkit/core": "^7.2.4",
    "@angular-devkit/schematics": "^7.2.4",
    "@angular/cli": "^7.2.4",
    "@angular/compiler": "^7.2.4",
    "@angular/compiler-cli": "^7.2.4",
    "@angular/language-service": "^7.2.4",
    "@ionic/angular-toolkit": "~1.2.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^10.12.26",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~8.0.0",
    "tslint": "~5.12.0",
    "typescript": "~3.1.6"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-x-socialsharing": {
        "ANDROID_SUPPORT_V4_VERSION": "24.1.1+"
      },
      "cordova-plugin-fcm-with-dependecy-updated": {},
      "ionic-plugin-deeplinks": {
        "URL_SCHEME": "mytest",
        "DEEPLINK_SCHEME": "https",
        "DEEPLINK_HOST": "test.mydomain.com",
        "ANDROID_PATH_PREFIX": "/",
        "ANDROID_2_PATH_PREFIX": "/",
        "ANDROID_3_PATH_PREFIX": "/",
        "ANDROID_4_PATH_PREFIX": "/",
        "ANDROID_5_PATH_PREFIX": "/",
        "DEEPLINK_2_SCHEME": " ",
        "DEEPLINK_2_HOST": " ",
        "DEEPLINK_3_SCHEME": " ",
        "DEEPLINK_3_HOST": " ",
        "DEEPLINK_4_SCHEME": " ",
        "DEEPLINK_4_HOST": " ",
        "DEEPLINK_5_SCHEME": " ",
        "DEEPLINK_5_HOST": " "
      }
    },
    "platforms": [
      "browser",
      "android",
      "ios"
    ]
  }
}

**Comment by eakoriakin** [comment]
package.json is also fine, can you reproduce the error with a StackBlitz repo?

**Comment by ViVer-7** [comment]
I tried to, but can't get it to work. Perhaps you can have a look?
[https://stackblitz.com/edit/ionic-h266pf](https://stackblitz.com/edit/ionic-h266pf)

**Comment by eakoriakin** [comment]
Try forking from https://stackblitz.com/edit/ionic-selectable-v4

**Comment by ViVer-7** [comment]
It seems to be working on stackblitz. Don't have the error there.
Perhaps incompatibillity with another external component?

**Comment by eakoriakin** [comment]
Maybe, try to get rid of dependencies one by one to find out which one is causing trouble. Check also if css is overridden by some other package.

**Comment by eakoriakin** [comment]
Closed for inactivity.

**Comment by shabbir-dhangot** [comment]
Getting same issue while executing test cases. My code as below.

    <ionic-selectable class="ionic-selectable-modal-md" formControlName="selectedrule" [items]="ruleList"
          itemValueField="ruleId" [(ngModel)]="newselectRule" itemTextField="ruleName" [canSearch]="true" (onChange)="ruleChange($event)"
          isMultiple="true" closeButtonText="X">
          <ng-template ionicSelectableItemIconTemplate let-port="item" let-isPortSelected="isItemSelected">
            <ion-icon item-left [name]="isPortSelected ? 'checkbox-outline' : 'square-outline'"
              [color]="isPortSelected ? 'primary' : null">
            </ion-icon>
          </ng-template>
        </ionic-selectable>
