### ISSUE TITLE
Select Icon desapears on Ionic 4 final

### ISSUE THREAD

**Issue by eduboxgithub** [eakoriakin/ionic-selectable#143]
I was using the latest version of this component on Ionic4-rc.0.

The component was working great, but now, since the final version of Ionic was release I updated to the final version, but the select icon disappeared.

When I press on a select the windows appears, the options are there (I can see the text) but the button to select them is not visible.

**With RC.0**
![image 3](https://user-images.githubusercontent.com/13800439/51833203-b8d46980-22ee-11e9-9da4-b0046cb78291.png)

**With final 4.0**
![image 3](https://user-images.githubusercontent.com/13800439/51833227-cb4ea300-22ee-11e9-8207-13952d1f0211.png)

**Comment by eakoriakin** [comment]
Hi, that a config + cache issue, take a look here:
https://github.com/ionic-team/ionic/issues/17019#issuecomment-452828443
