### ISSUE TITLE
Update ionic-selectable from a another source (e.g. second ionic-selectable)

### ISSUE THREAD

**Issue by glaenzesch** [eakoriakin/ionic-selectable#145]
Version: 4.2.0

✋ @ all,
i have a question regarding the array which stores the ids from the selected values.
I my case i have two multiselect ionic selectable components on one side. One for groups, and one for users. When i close the "group" component i want to search for the related users in my storage and mark them as selected inside the "users" component. I tried to fill the id array from the "users" component with different events (onSelect, onClose), but after i open the "users" component is crashes with some errors.

I tried to build up all in one component but i had no luck too
Does anyone have an idea or a hint for me?

Thank you very much.

**Comment by eakoriakin** [comment]
Hey, can you demonstrate it in StackBlitz?

**Comment by glaenzesch** [comment]
Hi @eakoriakin,

here is a rough example https://stackblitz.com/edit/ionic-selectable-basic-jdp4ho (based on your demo).
I can't make the ports "pre-selected" when i choose the country before.

**Comment by eakoriakin** [comment]
Hey, I did some changes to that StackBlitz sample, take a look.

**Comment by eakoriakin** [comment]
Actually, I couldn't save that sample, so just pasting code here:

**TS:**
```
import { Component } from '@angular/core';
import { IonicSelectableComponent } from 'ionic-selectable';
import { PortService } from '../../services';
import { Port, Country } from '../../types';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  ports: Port[];
  portNames: string[] = [];
  countries: Country[];
  countryNames: string[] = [];

  constructor(
    private portService: PortService
  ) {
    this.ports = this.portService.getPorts();
    this.countries = this.portService.getCountries();
  }

  countryChange(event: {
    component: IonicSelectableComponent,
    value: string[]
  }) {
    // event.value.forEach(element => {
    //    var temp = this.country.find(x=> x.name == element);
    //    temp.ports.forEach(port => {
    //      console.log(port.name);
    //      this.portids.push(port.name);
    //    });
    // });

    var portNames: string[] = [];

    event.value.forEach(selectedCountryName => {
      var selectedCountry = this.countries.find(country => country.name === selectedCountryName);
      portNames = portNames.concat(selectedCountry.ports.map(port => port.name));
    });

    console.log('portNames:', portNames);
    this.portNames = portNames;
  }

  portChange(event: {
    component: IonicSelectableComponent,
    value: any
  }) {
    console.log('port:', event.value);
  }
}
```

**HTML:**
```
<ion-header>
	<ion-navbar>
		<ion-title>Ionic Selectable v3</ion-title>
	</ion-navbar>
</ion-header>
<ion-content>
	<ion-item>
		<ion-label text-wrap>
			Basic usage.
		</ion-label>
	</ion-item>
	<ion-item>
		<ion-label>Country</ion-label>
		<ionic-selectable item-content [(ngModel)]="countryNames" itemValueField="name" itemTextField="name" [items]="countries"
		 [canSearch]="true" (onChange)="countryChange($event)" [shouldStoreItemValue]="true" [isMultiple]="true">
		</ionic-selectable>
	</ion-item>
	<ion-item>
		<ion-label>Port</ion-label>
		<ionic-selectable item-content [(ngModel)]="portNames" itemValueField="name" itemTextField="name" [items]="ports" [canSearch]="true"
		 (onChange)="portChange($event)" [shouldStoreItemValue]="true" [isMultiple]="true">
		</ionic-selectable>
	</ion-item>
</ion-content>
```

**Comment by glaenzesch** [comment]
Hey @eakoriakin,
thank you ver much. I updated the StackBlitz https://stackblitz.com/edit/ionic-selectable-basic-jdp4ho. Now i see the error in my application code as well.

Is there any possibility do this in one component? Something like this https://stackblitz.com/edit/ionic-selectable-basic-bfkwbn

By the way. Your work is really awesome. Thank you for this component.

**Comment by eakoriakin** [comment]
Thanks, regarding `Now i see the error in my application code as well.`.
https://stackblitz.com/edit/ionic-selectable-basic-jdp4ho works fine for me
