### ISSUE TITLE
How to simply search in ionicSelectableItemTemplate?

### ISSUE THREAD

**Issue by maedewiza** [eakoriakin/ionic-selectable#150]
I want to search in ionicSelectableItemTemplate of items. Can I do this simply, without thousands of lines of code? Can you help me to do this?

**Comment by eakoriakin** [comment]
Can you be more specific of what you? A code sample would be great.

**Comment by maedewiza** [comment]
```
ionic-selectable [(ngModel)]="prefix" [items]="country" [canSearch]="true">
        <ng-template ionicSelectableItemTemplate let-country="item">
          <ion-label>
            {{ country.code | flags }} {{ country.code }} ({{ country.dial_code }})
          </ion-label>
        </ng-template>
        <ng-template ionicSelectableValueTemplate let-country="value" class="center">
          {{ country.code | flags }} {{ country.code }} {{ country.dial_code }}
        </ng-template>
        <ng-template ionicSelectablePlaceholderTemplate>
          Select
        </ng-template>
```

I want to search simply in HTML's generated code of ionicSelectableValueTemplate, without separately accessing data for flags emoji (my pipe), country codes and dial codes.

**Comment by eakoriakin** [comment]
The thing is that `ionic-selectable` doesn't know anything about what's inside `ionicSelectableItemTemplate` and it actually **shouldn't know**. Templates are used to simply delegate HTML rendering of some parts to the end developer and they have nothing to do with search.

As I understand from your sample you want to do multi field search, meaning when user types something in searchbox all fields should be looked for a march, e.g. `country.code`, `country.dial_code`, etc.

To achieve it, you need to implement a search method. Take a look at the demo below, particularly at `filterPorts()`  method.
https://stackblitz.com/edit/ionic-selectable-on-search?file=pages/home/home.html

**Comment by maedewiza** [comment]
Could you see if OnSearch can be done better?
```
  async searchCountries(event: {
    component: IonicSelectableComponent,
    text: string
  }) {
    if (event.text) {
      const text = event.text.trim().toLowerCase().split(' ');
      let result;
      result = [];
      event.component.startSearch();
      result = (await this.country.filter((country) => {
        for (let i = 0; i < text.length; i++) {
          return country.code.toLowerCase().includes(text[i]) || country.dial_code.includes(text[i]) || country.flag === text[i];
        }
      }));
      event.component.items = result;
      event.component.endSearch();
    }
  }
```
