### ISSUE TITLE
placeholder not working

### ISSUE THREAD

**Issue by WuWeiWW** [eakoriakin/ionic-selectable#151]
### Source code
```
<ion-item>
            <ion-label position="undefined">车辆品牌</ion-label>
            <ionic-selectable placeholder="请选择..."
                              [items]="brandList"
                              clearButtonText="清除"
                              closeButtonText="返回"
                              itemValueField="id"
                              itemTextField="car_brand"
                              searchFailText="暂无"
                              searchText="输入关键字"
                              (onOpen)="onOpenBrand()"
                              [canSearch]="true">
            </ionic-selectable>
        </ion-item>
```
placeholder not working.If I open it ,then click close btn of ionic-selectable.the `placeholder` value can be show

### Page initialization completed
![p1](https://user-images.githubusercontent.com/6120411/53076717-55bfa680-352b-11e9-82c9-25b11bd00892.png)

### Selection data

![p3](https://user-images.githubusercontent.com/6120411/53076399-89e69780-352a-11e9-8f59-ab04dbf53faf.png)

### Do not choose
![p2](https://user-images.githubusercontent.com/6120411/53076472-b26e9180-352a-11e9-8706-a9be6ba4cabd.png)

### development environment
"@angular/core": "^7.2.2"
"ionic-selectable": "^4.3.0",
"@ionic/angular": "^4.0.0",
ionic4

###  Can you help me?

**Comment by pg16791** [comment]
![image](https://user-images.githubusercontent.com/26621278/83869121-afaca580-a749-11ea-99b7-6a6ee876583b.png)

It keeps loading

**Comment by pzontrop** [comment]
Why did you close this issue? Did you find a fix? I have the same issue on the latest version.
