### ISSUE TITLE
Error: Uncaught (in promise): IonicSelectable is disabled or already opened.

### ISSUE THREAD

**Issue by surajsingh-itian** [eakoriakin/ionic-selectable#155]
I'm using ionic-selectable@4.4.0 with ionic 4.10.1 
I'm starting with Basic usage, with static data, via lazy module (have imported `IonicSelectableModule` in main module as well as lazy loaded module), also as suggested have remove `item-content`.

On 1st click ionic-select searchable modal doesn't shows up and on 2nd click I get an error
> Error: Uncaught (in promise): IonicSelectable is disabled or already opened.

Can you let me know what might be causing this?

**Comment by yigitdemirbas** [comment]
Hi, we are having the same problem,
i think i found somethink about that,
on the first click an element occurs in the page,
Stressed in the picture

![selectable_error](https://user-images.githubusercontent.com/22319310/54496278-8b736780-48fe-11e9-95fa-eca80ea40456.png)

**Comment by glaenzesch** [comment]
> I'm using ionic-selectable@4.4.0 with ionic 4.10.1
> I'm starting with Basic usage, with static data, via lazy module (have imported `IonicSelectableModule` in main module as well as lazy loaded module), also as suggested have remove `item-content`.
> 
> On 1st click ionic-select searchable modal doesn't shows up and on 2nd click I get an error
> 
> > Error: Uncaught (in promise): IonicSelectable is disabled or already opened.
> 
> Can you let me know what might be causing this?

Hi, i don't have such a behaviour, becauseI import IonicSelectableModule  **only** in the page module where i'm using it. This works very nice.

**Comment by eakoriakin** [comment]
Check out v4 demo here https://stackblitz.com/edit/ionic-selectable-v4, you might have missed in the configuration on Ionic Project or Ionic Selectable module.

**Comment by gaurav-chandra** [comment]
I am also having this problem although I am using 3 ionic-selectable with different #ids. looks like it happens when the next ionic-selectable component is opened immediately. Will post a solution here.

**Comment by gaurav-chandra** [comment]
I had to use setTimeout for the next ionic-selectable to pass [items]="location" and had to stop ui interaction by showing a loader for 500 milliseconds. That helped with the issue.

**Comment by yigitdemirbas** [comment]
> I had to use setTimeout for the next ionic-selectable to pass [items]="location" and had to stop ui interaction by showing a loader for 500 milliseconds. That helped with the issue.

Could you upload an example to https://stackblitz.com/

**Comment by mamtakb** [comment]
@gaurav-chandra  kindly share your code to fix the code

**Comment by pkiruivits** [comment]
also with same issue

    <ion-item>
            <ion-label floating>Select Loan Type</ion-label>
            <select-searchable
              item-content 
              [(ngModel)]="ltypeid"
              [items]="ltypes"
              itemValueField="ltypeid"
              itemTextField="loantypename"
              [canSearch]="true"
              (onchange)="ltypechanged()"
             >
            </select-searchable>
          </ion-item>

**Comment by tqduy** [comment]
> Check out v4 demo here https://stackblitz.com/edit/ionic-selectable-v4, you might have missed in the configuration on Ionic Project or Ionic Selectable module.

Hi @eakoriakin 
I also face the same issue on v4 recently but with different behavior
==> When the option list is shown, I quickly double-click on an option to select it, the error will happens. 
Please take a look on this screenshot, I modify your sample code to follow the by-pass step [here](https://github.com/eakoriakin/ionic-selectable/wiki#ionicselectable-is-disabled-or-already-closed)
![image](https://user-images.githubusercontent.com/11729162/86094615-f5575680-bada-11ea-9d0b-0e6f0e72cb0a.png)
![image](https://user-images.githubusercontent.com/11729162/86094780-2df73000-badb-11ea-9a14-dc3ce4268de3.png)

Do you have any suggestion or am I missing something about configuration?

**Comment by znotdead** [comment]
Have same issue. Why is this closed? If you have selected item in the same place where select is (underneath of selected item) on double click it stays open and close() doesn't work anymore. Button `Close` doesn't work as well as any other selections.
I do not have any specific setup and do not call `close` manually. footer template is not passed, not multiple, no confirm button. so issue is somewhere here I think https://github.com/eakoriakin/ionic-selectable/blob/e3b44a46fa5c372d2b947c380567e6263b44eb83/src/app/components/ionic-selectable/ionic-selectable.component.ts#L1182

**Comment by loneoakdev** [comment]
I can't seem to get past this issue when actually deployed on to an iOS device. Testing works fine in the browser (although I can still see the error message in the console). When testing through Xcode an actual iPhone though, I get the following error in the Xcode console and the modal with the options never pops up:

[error] - ERROR IonicSelectable is disabled or already opened.

I'm using Angular 17 standalone with Ionic 7, so my standalone component is configured with IonicSelectableComponent and I specified the Ionic ModalController as a provider.

Any other possible solutions for this issue? Thanks
