### ISSUE TITLE
How to set a Default Dropdown Value from TS File in ionic-selectable?

### ISSUE THREAD

**Issue by amitalgo** [eakoriakin/ionic-selectable#156]

**Comment by eakoriakin** [comment]
Via `ngModal`:

```
<ionic-selectable item-content
  [(ngModel)]="port"
  itemValueField="id"
  itemTextField="name"
  [items]="ports">
</ionic-selectable>
```

```
  ngOnInit() {
    this.port = { id: 1, name: 'MyPort' };
  }
```

**Comment by amitalgo** [comment]
I am getting only name so in that case i can i preselect the value?

**Comment by eakoriakin** [comment]
Not sure I understand, can you add some code sample?

**Comment by amitalgo** [comment]
I have got the answer this.sampleForm.controls['portControl'].setValue({ name: portName });

**Comment by cerge** [comment]
Sorry, amitalgo, it didnt worked for me, Evgenii, do you know if we can select a default value on each selectable control when we load the form in ionic 3? I mean, by sample: 0 , Zero or No value

**Comment by rathodkaran07** [comment]
Hey @eakoriakin ,

Can we set default value only by id? I do not get value from backend !!
Please help

**Comment by eakoriakin** [comment]
It can work without `id`, in this case you just need to pass an array of primitive types. Check out this demo:
https://stackblitz.com/edit/ionic-selectable-primitive-types?file=pages/home/home.html

**Comment by vishwas097** [comment]
@eakoriakin  Is there any possibility to set the default option via typescript? [(ngModel)] is not working in my case? If any workaround available please let me know.
