### ISSUE TITLE
Unable to access array element in embedded object

### ISSUE THREAD

**Issue by FireSol** [eakoriakin/ionic-selectable#157]
Hi Evgenii,

Firstly, thanks for sharing such a great component. 

I am having some issues creating > itemTextField > where I am trying to show a field that is present within an embedded object, as follows:

[id:'xxx', 
fields: model: "model_name", type: "type_name"]

I want to reference the embedded "model_name" value but am unable to parse it from the 'fields' array and am hoping that you could point me in the right direction?

Please excuse any incorrect statements above; I am relatively new to coding!!

Thanks
Mark

**Comment by eakoriakin** [comment]
Hey, as for now `itemTextField` option supports only root fields, e.g. `item.name`, but you can use `item tempate` to render any text you need:
https://github.com/eakoriakin/ionic-selectable/wiki#item-template
