### ISSUE TITLE
Control over label when selection has been made.

### ISSUE THREAD

**Issue by SteynMarnus** [eakoriakin/ionic-selectable#159]
Firstly, a huge fan of the component, absolutely heaven sent!

I would like to know if it would be possible for a small addition in which you can set the text of the label at the end slot of the control after you have made a selection. A use case would make more sense I present you with the following:

I set the component to be able to make multiple selections (`isMultiple=true`), After selection a bunch of items and the modal has been closed, instead of displaying them one after the other, have the label read, "Selection made" or "Selected" and not a list of the items that were selected. So instead of [this](https://ibb.co/zSG0PR4) approach, have control over label text like for example [this](https://ibb.co/xhMz6M5)

**Comment by eakoriakin** [comment]
Hey, thanks a lot! It's for sure possible with a [value template](https://github.com/eakoriakin/ionic-selectable/wiki#multiple-values-template):

```
<ionic-selectable [isMultiple]="true" item-content
  [(ngModel)]="selectedPorts" itemValueField="id"
  itemTextField="name" [items]="ports">
  <ng-template ionicSelectableValueTemplate let-ports="value">
    {{ports.length ? 'Selected' : ''}}
  </ng-template>
</ionic-selectable>
```
