### ISSUE TITLE
Reactive Form Validation 

### ISSUE THREAD

**Issue by eugene-ilchenko-techjam** [eakoriakin/ionic-selectable#160]
I have an issue with reactive form validation using this plugin, when the field was touched, no actions happen - the field not highlighted with the red line, like for default ion-item

steps for reproduce: click ionic-selectable -> click cancel 

ts file
`this.orderForm = this.fb.group({
      customer_organization_id: ['', Validators.compose([Validators.required])]
});`

 html:

`<ion-item>
        <ion-label position="floating" for="customer_organization_id" class="order-label">
          Shipping Organization
        </ion-label>
        <ionic-selectable
          formControlName="customer_organization_id"
          [items]="organizations"
          itemValueField="id"
          itemTextField="name"
          [canSearch]="true"
          (onChange)="organizationChanged($event)">
        </ionic-selectable>
      </ion-item>
      <div ngxErrors="customer_organization_id">
        <div class="error" ngxError="required" [when]="['dirty', 'touched', 'pristine']">
          Field is required
        </div>
      </div>`

The reason that ion-item have not any class like "ion-touched ion-dirty ion-invalid" after event

how to fire form validation in this case?

**Comment by eakoriakin** [comment]
What version of `ionic-selectable` do you use?
Also, please provide a StackBlitz dem, such as [this one](https://stackblitz.com/edit/ionic-selectable-basic), so I could reproduce the behavior.

**Comment by eugene-ilchenko-techjam** [comment]
I am using Ionic 4 so I choose:
ionic-selectable@4.4.0 

I have tried ionic v3 on StackBlitz, it works perfect, I was trying to create the same on v4, and gon an error just added IonicSelectableModule to app.module.ts, not sure how to reproduce this for version 4 there:

https://stackblitz.com/edit/ionic-v4-bvwpsz

**Comment by eakoriakin** [comment]
Try forking from https://stackblitz.com/edit/ionic-selectable-v4
