### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by tiagosilveiraa** [eakoriakin/ionic-selectable#161]
When I Type in the search Field it does not filter the array content keeps showing me all the array content.

As you can see below:
(http://prntscr.com/n0rjhw)

`Ionic 4.12.0`
`Angular 7.2.4`

Heres my Markup:
```
              <ionic-selectable
                formControlName="tipoTarefa"
                [items]="tiposTarefas"
                itemValueField="id"
                itemTextField="descricao"
                [canSearch]="true"
                closeButtonText="Fechar"
                (onChange)="tipoTarefaChange($event)">
              </ionic-selectable>


```

**Comment by eakoriakin** [comment]
You must have missed something. Please refer to the demo below:
https://stackblitz.com/edit/ionic-selectable-basic?file=app%2Fpages%2Fhome%2Fhome.ts

**Comment by tiagosilveiraa** [comment]
I've Built my HTML using this demo as reference, and it does not work, here is my TS if u want to see:
[My TS]
(https://github.com/tiagosilveiraa/PManager/blob/master/src/app/private/sharedmodule/tarefas-detalhe/tarefas-detalhe.page.ts)

When I Try to select one of the items of the list it works perfectly but when I Try to seach one, it does'not filter. In Browser simulation IOS The screen blinks and the app just don't filter

look the gifs below, please!

[IOS] (https://prnt.sc/n1314f)
[Android] (https://prnt.sc/n131kw)

On android mode I Don't even type and the screen keeps blinking, Here's all my components:
[](https://github.com/tiagosilveiraa/PManager/tree/master/src/app/private/sharedmodule/tarefas-detalhe)

Please, help me.
