### ISSUE TITLE
ItemTemplate: Iterate through list of items with line break

### ISSUE THREAD

**Issue by glaenzesch** [eakoriakin/ionic-selectable#165]
Hi @eakoriakin,
today i have a question about the _ ionicSelectableItemTemplate_. Is it possible to iterate through a list of items and add a line break after each one?
I tried already with `<br>` and `.join(<br>)`, but nothing worked like expected.

Please see this StackBlitz: https://stackblitz.com/edit/ionic-selectable-item-template-7z45ch

Thanks, 
glaenzesch

**Comment by eakoriakin** [comment]
Have you tried grouping?
https://github.com/eakoriakin/ionic-selectable/wiki#grouping-items

**Comment by glaenzesch** [comment]
That's not what want. This is the current situation:

1. I have to display elements. 
2. These elements have on id and one or more names, or let's say labels.
3. So I want to display all labels for one element in separate lines and store only the id.

Of course later one i have to adjust the search textbox.

**Comment by eakoriakin** [comment]
You can also try customizing item content with [item-template](https://github.com/eakoriakin/ionic-selectable/wiki#item-template) to render a list of things inside each item as follows:

```
<ionic-selectable itemValueField="id" itemTextField="name" [items]="countries">
  <ng-template ionicSelectableItemTemplate let-country="item">
    <ion-label *ngFor="let port of country.ports">
      {{port.name}}
    </ion-label>
  </ng-template>
</ionic-selectable>
```
