### ISSUE TITLE
 Changing searchText not working

### ISSUE THREAD

**Issue by LautaroLorenz** [eakoriakin/ionic-selectable#166]
Hello,
I am trying to change the text "search"
I used the property "searchText" and also "placeholder" but it did not work with any of these options
```
<ionic-selectable 
          item-content
          formControlName="equipo"
          itemValueField="imei"
          itemTextField="nombre"
          [items]="[emptyEquipo].concat(equipoSv.equiposSubject | async)"
          [canSearch]="true"
          searchText="Buscar"
          placeholder="Buscar"
          (onChange)="filtrosForm.ngSubmit.emit()">
          <ng-template ionicSelectableCloseButtonTemplate>
            <ion-icon name="close-circle" style="font-size: 24px;"></ion-icon>
          </ng-template>
        </ionic-selectable>
```
Result:
![image](https://user-images.githubusercontent.com/21241657/55800916-36fd7b00-5aab-11e9-9474-ce85e916ca47.png)

The word "search" continues to appear

**Comment by eakoriakin** [comment]
Hi, the field you are looking for is searchPlaceholder:
https://github.com/eakoriakin/ionic-selectable/wiki#searchplaceholder

**Comment by LautaroLorenz** [comment]
thank you very much, it is exactly what I was looking for
