### ISSUE TITLE
Build error: Property '_cssClass' is private and only accessible within class 'IonicSelectableComponent'.

### ISSUE THREAD

**Issue by nvelin-zaggo** [eakoriakin/ionic-selectable#167]
Hi, I have a build error (I'm using @ionic/angular@4.2.0, and ionic-selectable@4.4.0). I'm using lazy loading and everything is configured correctly.

`
Error: projects/ui-mobile/src/lib/pages/profile/profile.page.html(83,29): : Directive IonicSelectableComponent, Property '_cssClass' is private and only accessible within class 'IonicSelectableComponent'.
projects/ui-mobile/src/lib/pages/profile/profile.page.html(83,29): : Directive IonicSelectableComponent, Property '_isMultipleCssClass' is private and only accessible within class 'IonicSelectableComponent'.
projects/ui-mobile/src/lib/pages/profile/profile.page.html(83,29): : Directive IonicSelectableComponent, Property '_hasValueCssClass' is private and only accessible within class 'IonicSelectableComponent'.
projects/ui-mobile/src/lib/pages/profile/profile.page.html(83,29): : Directive IonicSelectableComponent, Property '_hasPlaceholderCssClass' is private and only accessible within class 'IonicSelectableComponent'.
projects/ui-mobile/src/lib/pages/profile/profile.page.html(83,29): : Directive IonicSelectableComponent, Property '_hasIonLabelCssClass' is private and only accessible within class 'IonicSelectableComponent'.
projects/ui-mobile/src/lib/pages/profile/profile.page.html(83,29): : Directive IonicSelectableComponent, Property '_hasDefaultIonLabelCssClass' is private and only accessible within class 'IonicSelectableComponent'.
projects/ui-mobile/src/lib/pages/profile/profile.page.html(83,29): : Directive IonicSelectableComponent, Property '_hasFixedIonLabelCssClass' is private and only accessible within class 'IonicSelectableComponent'.
projects/ui-mobile/src/lib/pages/profile/profile.page.html(83,29): : Directive IonicSelectableComponent, Property '_hasStackedIonLabelCssClass' is private and only accessible within class 'IonicSelectableComponent'.
projects/ui-mobile/src/lib/pages/profile/profile.page.html(83,29): : Directive IonicSelectableComponent, Property '_hasFloatingIonLabelCssClass' is private and only accessible within class 'IonicSelectableComponent'.
`

Could you please check? Thanks.

**Comment by eakoriakin** [comment]
Hi, should be fixed now in [4.4.1](https://github.com/eakoriakin/ionic-selectable/releases/tag/4.4.1) release.
