### ISSUE TITLE
Can i use ionic-selectable in *ngFor

### ISSUE THREAD

**Issue by tanutsun** [eakoriakin/ionic-selectable#169]
I want to use dynamic select.
I try to use

```
<ion-item *ngFor="let att of anArray; let idx = index">
          <ion-icon item-start name="custom-icon-user"></ion-icon>
          <ion-label stacked>Member {{idx + 1}}</ion-label>
          <ionic-selectable name="{{idx}}"
            item-content
            [(ngModel)]="anArray[idx].value"
            [items]="userList"
            itemValueField="id"
            itemTextField="name"
            [canSearch]="true"
            (onChange)="changeMember(idx,$event)">
          </ionic-selectable>
</ion-item>
```

but dosen't work

Thank you for help.

**Comment by eakoriakin** [comment]
Hi, yes it should be fine wtih `ngFor`. Not sure why it doesn't work for you.
Try using `FormArray` instead:
https://stackblitz.com/edit/ionic-selectable-form-array?file=app/pages/home/home.ts

**Comment by tanutsun** [comment]
That work. Thank you.

**Comment by ajakl5** [comment]
Hi Evgenii Koriakin,

I have downloaded your project from stackblitz (ion-selectable with formarray).

Steps followed to test it locally in my development:
1. extracted zip
2. npm update
3. ionic init
    installed ionic scripts
4. ionic serve Error

Error: tsconfig: Cannot read file '/home/ajay/src/coder/tester/tsconfig.json': ENOENT: no such file or 
[app-scripts]             directory, open '/home/ajay/src/coder/tester/tsconfig.json'. 

Any help is appreciated.

Also what can I do to clear following warnings:

npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"10.20.1","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/compiler-cli@6.1.1 requires a peer of typescript@>=2.7.2 <2.10 but none is installed. You must install peer dependencies yourself.
npm WARN tsickle@0.32.1 requires a peer of typescript@>=2.4.2 <2.10 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

Thanks

Ajay K
