### ISSUE TITLE
white-space normal in select items

### ISSUE THREAD

**Issue by camdenl** [eakoriakin/ionic-selectable#170]
Is there any way to set the white-space as normal for the ion-label items?

For instance from this:

![image](https://user-images.githubusercontent.com/5865994/56683435-880c9200-669b-11e9-8d15-77e7cae9c434.png)

To this:

![image](https://user-images.githubusercontent.com/5865994/56683472-9e1a5280-669b-11e9-9aaf-c1f611c89d46.png)

**Comment by eakoriakin** [comment]
Yes, you can wrap items in `ion-label` using [ionicSelectableItemTemplate](https://github.com/eakoriakin/ionic-selectable/wiki#item-template):

```
<ionic-selectable>
  <ng-template ionicSelectableItemTemplate let-port="item" let-isPortSelected="isItemSelected">
    <ion-label text-wrap>
      {{port.name}} ({{port.country.name}})
    </ion-label>
  </ng-template>
</ionic-selectable>
```

**Comment by camdenl** [comment]
Awesome man, thanks.  This component is amazing!
