### ISSUE TITLE
change searchbar background color

### ISSUE THREAD

**Issue by sneha199704** [eakoriakin/ionic-selectable#173]
![backgroundimage](https://user-images.githubusercontent.com/48767226/57077499-d52adc80-6d09-11e9-8789-4f30b0783520.png)
i am using ionic-selectable in ionic 4 application i want change searchbar background color same as a header color 
here is my code:
    <ionic-selectable item-content headerColor="primary"  [(ngModel)]="userModel.state" formControlName="state" [items]="statesList"
        itemValueField="stateID" itemTextField="state" [canSearch]="true" [shouldStoreItemValue]="true" >
        <ng-template ionicSelectableItemTemplate let-port="item">
          {{port.state}} ({{port.stateID}})
        </ng-template>
      </ionic-selectable>

**Comment by rtcimi** [comment]
<ionic-selectable **modalCssClass="ionic-selectable-documentation-configuration"**>
</ionic-selectable>

.ionic-selectable-documentation-configuration {
        .modal-wrapper {
            ionic-selectable-modal {
                ion-header {
                    ion-toolbar {
                        --background: var(--ion-color-dark);
                    }
                }

                ion-searchbar {
                    --background: var(--ion-color-dark);

                    .searchbar-input {
                        background: transparent;
                        color: #fff;
                        box-shadow: unset;
                    }

                    .searchbar-search-icon {
                        color: #fff;
                    }

                    .searchbar-clear-button {
                        color: #fff;
                    }
                }

                ion-footer {
                    background: var(--ion-color-dark);

                    ion-toolbar {
                        --background: var(--ion-color-dark);

                        ion-button {
                            display: inline-block !important;
                            --background: var(--ion-color-warning);
                        }
                    }
                }
            }
        }
    }

Modify as needed **+ it is mendatory that style is added to variables.scss**

**Comment by vinod0354** [comment]
How to change confirmation  button background color
