### ISSUE TITLE
Ionic selectable modal takes a time to load on click

### ISSUE THREAD

**Issue by developuser** [eakoriakin/ionic-selectable#174]
When i click the ionic-selectable it should take a time to open the modal so during this time how i set the spinner for loading the model

**Comment by eakoriakin** [comment]
Try [showLoading()](https://github.com/eakoriakin/ionic-selectable/wiki#showloading) and [hideLoading()](https://github.com/eakoriakin/ionic-selectable/wiki#hideloading).
