### ISSUE TITLE
Problem with binding data in a bidimensional associative array 

### ISSUE THREAD

**Issue by minipisame** [eakoriakin/ionic-selectable#175]
Hello everyone, 
I am working in a proyect where I take out a data in a bidimensional associative array  like this 
![image](https://user-images.githubusercontent.com/44228797/58234237-6526d980-7d3e-11e9-9041-5bc1da724c67.png)
 I have problem binding the data name.esp with the property itemTextField because this don't acces s to the data correctly but i can access to id correctly so the problem is access to a map parameter.
This is the result
![image](https://user-images.githubusercontent.com/44228797/58234544-19c0fb00-7d3f-11e9-8a5a-5ba377772b33.png)
And this is my html code for the ionic selectable where activityTags is the array show before
![image](https://user-images.githubusercontent.com/44228797/58234603-39f0ba00-7d3f-11e9-9b4a-a73d59ce229f.png)

Thanks for the troubles.

**Comment by eakoriakin** [comment]
Hey, just use [item-template](https://github.com/eakoriakin/ionic-selectable/wiki#item-template) to format the output the way you want.
