### ISSUE TITLE
How to put close button near OK 

### ISSUE THREAD

**Issue by SanduCuragau** [eakoriakin/ionic-selectable#177]
Cheers I've been using this package for a couple of days and it totally saved my ass, but I still haven't finished what I've got to do, and one of the requirements is to have the cancel button at the bottom near the ok, like what it looks like when you have the clear button showing, is there any way to bring the cancel button there? Because I've tired and the docs only suggest using the ionic slots so I'm really lost here but it's such an important detail

http://prntscr.com/nubpx1

**Comment by eakoriakin** [comment]
There are two ways to add Cancel button:
1. In the headder using slots, as you mention in your post - [closeButtonSlot](https://github.com/eakoriakin/ionic-selectable/wiki#closebuttonslot), [closeButtonTemplate](https://github.com/eakoriakin/ionic-selectable/wiki#close-button-template), [closeButtonText](https://github.com/eakoriakin/ionic-selectable/wiki#closebuttontext).
2. In the footer using [footer template](https://github.com/eakoriakin/ionic-selectable/wiki#footer-template).
```
<ionic-selectable #portComponent [canClear]="true">
  <ng-template ionicSelectableFooterTemplate>
    <ion-toolbar>
      <ion-row>
        <ion-col>
          <button ion-button full (click)="portComponent.close()">
            Cancel
          </button>
        </ion-col>
        <ion-col *ngIf="portComponent.canClear">
          <button ion-button full (click)="clear()"
            [disabled]="!portComponent.itemsToConfirm.length">
            {{portComponent.clearButtonText}}
          </button>
        </ion-col>
        <ion-col>
          <button ion-button full (click)="portComponent.confirm(); portComponent.close();">
            {{portComponent.confirmButtonText}}
          </button>
        </ion-col>
      </ion-row>
    </ion-toolbar>
  </ng-template>
</ionic-selectable>
```
