### ISSUE TITLE
Implement infinitescroll without observables

### ISSUE THREAD

**Issue by tiagosilveiraa** [eakoriakin/ionic-selectable#179]
Hello,

It is not a issue exacly, but is a doubt. How can I implement infinitescroll without observables, subscriptions and etc..., in the demo it is used, but in my case I just have one const with thousands of cities and a should load then 20 by 20 and I really cannot do that

I stuck on a logic problem, i think, because the first page is loaded correctly, but i cannot keep loading the pages from  where i stopped as you can see below:

![STACKOVERFLOW1](https://user-images.githubusercontent.com/24441478/58848522-53f29c80-865d-11e9-9ea3-22834be54850.gif)

my function:
```
  getCities() {
    this.cities= this.addressService.getCities(this.page);
  }
  getMoreCities(event: {
    component: IonicSelectableComponent,
    text: string
  }) {

 
    if (this.page > 50) { //50 IS JUST AN EXAMPLE
      event.component.disableInfiniteScroll();
      return;
    }
    event.component.items.concat(this.addressService.getCities(this.page++));
  }
```
Here's my service:

    getCities(page?: number): any[] {
        let cities= [];

        cities= this.cities.slice((page* 10), 20);

        return cities;
    }

The const that i'm reading and import as a property of my service:

```
export const CITIES= [
    {
        "code": 1100015,
        "city_name": "Alta Floresta D'Oeste",
        "uf": "RO"
    },
    {
        "code": 1100023,
        "city_name": "Ariquemes",
        "uf": "RO"
    },
    {
        "code": 1100031,
        "city_name": "Cabixi",
        "uf": "RO"
    },
    {
        "code": 1100049,
        "city_name": "Cacoal",
        "uf": "RO"
    }] //THERE ARE MORE...
```

I've made my best to translate whe non english words, but i'm a bit desperate.

**Comment by eakoriakin** [comment]
Did you see this demo:
https://stackblitz.com/edit/ionic-selectable-infinite-scroll?file=pages/home/home.html
