### ISSUE TITLE
Error: typeerror cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by cerge** [eakoriakin/ionic-selectable#182]
Hi friends, sorry i receive this error running a app with ionic 3.
Basically I use 'id' like field value item in a control with this code in ts file, when i want to insert in local sqlite database:
 
//I tried to resume insert line because i use 50 fields:
`  sqlinsert = "INSERT INTO vet_auditorias( Mat) VALUES ( "+this.myForm.value.Mat['id']+")"; `

My ionic html is like this:

```
 <ion-item>
                      <ion-label>Mat</ion-label>
                      <ionic-selectable        
                        item-content  
                        formControlName="Mat"            
                        [(ngModel)]="modelodb5"
                        [items]="modelos5"            
                        itemValueField="id"
                        itemTextField="matricula"
                        [canSearch]="true"
                        (onChange)="modeloCambio($event)">
                      </ionic-selectable>
</ion-item>
```
thanks in advance for some tip or help!

**Comment by eakoriakin** [comment]
Please provide more info about the error.

Meanwhile, I’m closing the issue as it doesn’t seems to be related to the component itself.
