### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ritesh2496** [eakoriakin/ionic-selectable#183]
Hello
Some one have the solution to make it work with ionic 4 ?

_Originally posted by @jbdioli in https://github.com/eakoriakin/ionic-selectable/issues/80#issuecomment-485468694_

**Comment by eakoriakin** [comment]
Hi, have you tried v4?

`npm install ionic-selectable@4.4.0 --save`

**Comment by jbdioli** [comment]
It works like this :

https://www.youtube.com/watch?v=SO_AWrrmZlY

**Comment by ritesh2496** [comment]
Yes i have tried that but it is not working

**Comment by terranmarine** [comment]
Hello @ritesh2496 I am currently using ionic-selectable with ionic v4. Works fine. Can you please provide some code?

**Comment by ritesh2496** [comment]
Thnq for your help but now i am abel to work on it and it is working fine.
I just needed to update the angular and npm in my ionic 4 project. Thnq for
the help.
