### ISSUE TITLE
Ionic  Selectable field inside Modal

### ISSUE THREAD

**Issue by schagani** [eakoriakin/ionic-selectable#184]
Hi

I am using ionic-selectable in Ionic 3. The issue which I am facing is that the dropdown of ionic-selectable doesn't get updated when user selected a value while using it in ionic modal. It is working fine when use page instead of modal.

Any suggestion

Cheers
Sheheryar

**Comment by terranmarine** [comment]
What do you mean by 'it doesn't get updated?' Can you provide an example. Also you can try to update it manually.

**Comment by schagani** [comment]
Means it is not showing selected value in the select field.

**Comment by terranmarine** [comment]
Please provide some code.

**Comment by eakoriakin** [comment]
Would be great to see a replication on StackBlitz or a git repo. Closing it until then.
