### ISSUE TITLE
Searches with accents

### ISSUE THREAD

**Issue by gustavoucm** [eakoriakin/ionic-selectable#185]
Hi. I'm programming an app but it's in Spanish so when I try to search a word with accents they're ignored. I woudl like to know if there's any way to do searches regardless of whether they have accents or not.

**Comment by eakoriakin** [comment]
Hi, you are looking for onSesrch event to override default search algorithm. Here is a sample:

https://stackblitz.com/edit/ionic-selectable-on-search?file=pages/home/home.html

**Comment by gustavoucm** [comment]
Thanks a lot. That works
