### ISSUE TITLE
When I clicked a option, it paint many other options

### ISSUE THREAD

**Issue by cerge** [eakoriakin/ionic-selectable#187]
Please, if some expert can help me, My code is almost ready but when i test the ionic-selectable component happens this issue.
I mean, When I clicked a option, it paint many other options. My html is:
`        <ion-item>
                <ion-label >Habilitacion Farmacia (por numero)</ion-label>
                  <ionic-selectable
                    item-content 
                    formControlName="HabilitacionNro"     
                    [(ngModel)]="modelodb"
                    [items]="modelos"
                    itemValueField="id"
                    itemTextField="habilitacionnumero"
                    [canSearch]="true"
                    (onChange)="modeloCambio($event)">
                  </ionic-selectable>
              </ion-item>`

 

and ts file:
`     async cargarhabilitacion1(){
          
        
                  const response = await this.sqliteService.executeSql('SELECT Nombre, HabilitacionNumero FROM vet_establecimientos ')
                
                  let hab1 = [];
                  if (response.rows.length > 0) {
                    for (var i = 0; i < response.rows.length; i++) {

                      //controlador:
                      hab1.push({id: response.rows.item(i)['HabilitacionNumero'], habilitacionnumero: response.rows.item(i)['HabilitacionNumero'] + " " + response.rows.item(i)['Nombre']});
                    
                    } //for
                  } //if
                  console.log(JSON.stringify(hab1));
                  return hab1;

        
         }`
Thanks in advance for some help!

**Comment by 8tomo8** [comment]
This is likely because your ID's are duplicated. Make sure your ID's are unique. You can just assign itemValueField to the name and it should be fine.
