### ISSUE TITLE
A question how this could be solved with the selectable field:

### ISSUE THREAD

**Issue by cschoeni** [eakoriakin/ionic-selectable#192]
Backend
The backend has a field called item_id and waits for a number (id).

The objects items are loaded in an array and displayed in the selectable field in a reactive form. 

If now a value is selected, only the id is to be set as value.

If a value e.g. id 7 was stored, the object is to be found with the help of the id when loading the form.

How can this be solved?

**Comment by Vaweila** [comment]
Look into https://github.com/eakoriakin/ionic-selectable/wiki#itemvaluefield and https://github.com/eakoriakin/ionic-selectable/wiki#itemtextfield.

If you have an array of objects like [{id: 1, value: 'text1'}, {id: 2, value: 'text2'}] you can use these properties to tell the form what it should show to the user and what it should save as a value when the user clicks the item.

**Comment by eakoriakin** [comment]
What you are looking for is [shouldStoreItemValue](https://github.com/eakoriakin/ionic-selectable/wiki#shouldstoreitemvalue) option.
