### ISSUE TITLE
change select icon position to the right

### ISSUE THREAD

**Issue by taltalit** [eakoriakin/ionic-selectable#193]
this plugin is awesome
how can i change the select icon to the right?
![05e14e1e77d810b2e1f2991e931be0d49f0dabf3](https://user-images.githubusercontent.com/2332139/63939354-c5c95f00-ca6f-11e9-9cc1-702d07e79569.png)

**Comment by eakoriakin** [comment]
It should be possible with [itemIconSlot](https://github.com/eakoriakin/ionic-selectable/wiki#itemiconslot), but only supported with with `Ionic 4` and `ionic-selectable@4.4.0`.
