### ISSUE TITLE
onSelect event doesn't work on unselection

### ISSUE THREAD

**Issue by mikepoulpe** [eakoriakin/ionic-selectable#194]
I have a ionic-selectable with the (onSelect)="onSelect($event)" event.

Everything is alright when I select an option.
But that's doesn't work when I unselect. 

Nothing happen when I unselect an option ... If I reopen the selectable again my option is selected.

Working on ionic 3 with ionic selectable 3-4-0

**Comment by eakoriakin** [comment]
There's no option to unselect a selected item by default. However, what you can do is:
1. Enable [canClear](https://github.com/eakoriakin/ionic-selectable/wiki#canclear) option.
https://stackblitz.com/edit/ionic-selectable-can-clear?file=pages/home/home.html
2. Or allow multiple selection with [isMultiple](https://github.com/eakoriakin/ionic-selectable/wiki#ismultiple). Then you can actually unselect options.
https://stackblitz.com/edit/ionic-selectable-is-multiple?file=pages/home/home.html
