### ISSUE TITLE
Is there any way to custom the arrow icon in the selectable item?

### ISSUE THREAD

**Issue by pdlm95** [eakoriakin/ionic-selectable#195]
Hello! I'm trying to edit the color property of the icon in the selectable item

Ex: 
.ionic-selectable-icon-inner{
color: red !important;
}

I know it's possible somehow because I can change the property in dev mode, but it doesn't work in my CSS. Any idea what I'm doing wrong?

Ionic:
   ionic (Ionic CLI)             : 4.12.0 
   Ionic Framework               : @ionic/angular 4.3.1
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:
   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)

![screen_1](https://user-images.githubusercontent.com/54819321/64132417-c3337600-cd9d-11e9-8902-77be8cab02d7.PNG)
![screen_2](https://user-images.githubusercontent.com/54819321/64132421-c890c080-cd9d-11e9-8253-f6a721911836.PNG)

**Comment by eakoriakin** [comment]
Try this selector:
```
.ionic-selectable-md .ionic-selectable-icon-inner {
  color: red;
}
```

**Comment by pdlm95** [comment]
Unfortunately it still doesn't work for me, neither with !important tag
