### ISSUE TITLE
Doesn't show value on page load when itemValueField is string

### ISSUE THREAD

**Issue by dewebeloper** [eakoriakin/ionic-selectable#196]
Hi
I face a strange thing...
Issue is when I use guid string for itemValueField.
If I use this line
`this.form1Control = this.formBuilder.control('02710755-ae13-4a10-9a39-5270f51adfcc',  Validators.required);`
where '02710755-ae13-4a10-9a39-5270f51adfcc' is existing Id from array I don't get populated value in ionic-selectable. Also, form apparently looks like valid, and if I reset form control value then is invalid.

On examples where array.id is number looks like it works ok (example https://stackblitz.com/edit/ionic-selectable-form-control?file=pages/home/home.html)

I made fork with issue on https://stackblitz.com/edit/ionic-selectable-form-control-ajlgc5?file=pages/home/home.html.

Issue is on ionic v3.

**Comment by eakoriakin** [comment]
You need to provide a full object to FormControl as a value:

```
this.form1Control = this.formBuilder.control(Opstine.opstine[0],  Validators.required)
```

Alternatively, if you wish to keep only an id as a value of FormControl then use `shouldStoreItemValue`:
https://github.com/eakoriakin/ionic-selectable/wiki#shouldstoreitemvalue

**Comment by dewebeloper** [comment]
Coo, that's fixed all. Thanks
