### ISSUE TITLE
HELP WANTED : Smaller Font size in the selectable modal

### ISSUE THREAD

**Issue by dverma** [eakoriakin/ionic-selectable#197]
Is there a way to change the font size for the labels in Selectable modal? I have multiple options which are considerably long and differ on the last few characters which get cut out by ellipsis.

Thanks in advance.

**Comment by eakoriakin** [comment]
There're two ways to change it:
1. Try changing CSS.
2. Or use custom [item template](https://github.com/eakoriakin/ionic-selectable/wiki#item-template).
Demo: https://stackblitz.com/edit/ionic-selectable-item-template?file=app/pages/home/home.html

**Comment by dverma** [comment]
Thanks @eakoriakin 
Custom item template worked like a charm. 👍
