### ISSUE TITLE
Unable to Change Ionic Selectable Icon

### ISSUE THREAD

**Issue by MalikHerring** [eakoriakin/ionic-selectable#198]
![image](https://user-images.githubusercontent.com/24815498/65066498-b0927280-d941-11e9-9f76-e11c2e48ec86.png)

I would like to be able to change the icon that is circled in the picture. 
I would like to use a custom icon or potentially a different ion-icon. 
It would be nice to also be able to remove the icon entirely at will.

**Comment by edy-ap** [comment]
this feature will be added in the next version

**Comment by edy-ap** [comment]
feature added in v4.6.0 and v3.5.0

**Comment by edy-ap** [comment]
feature added in v4.6.0 and v3.5.0
