### ISSUE TITLE
Ionic 5 support

### ISSUE THREAD

**Issue by heinzburgstaller** [eakoriakin/ionic-selectable#204]
Ionic 5 will have some breaking changes
https://github.com/ionic-team/ionic/releases/tag/v5.0.0-beta.0

Please streamline the components code

**Comment by edy-ap** [comment]
I've added a pr to fix it
https://github.com/eakoriakin/ionic-selectable/pull/206

**Comment by edy-ap** [comment]
the breaking changes were already fixed in version 4.5.0, the issue will remain open until it is updated to the ionic 5 version

**Comment by jalexc** [comment]
I've also added related PR #212

**Comment by edy-ap** [comment]
thanks, it fixed in release 4.5.2, is now available on npm
