### ISSUE TITLE
ionic-selectable-cover take full height

### ISSUE THREAD

**Issue by niczm25** [eakoriakin/ionic-selectable#207]
Upon checking elements why ionic-selectable's dynamic search open anywhere, I saw ionic-selectable-cover button takes full height that would triggered canSearch page.

**Comment by edy-ap** [comment]
Can you upload a example image, or code, thanks

**Comment by niczm25** [comment]
> Can you upload a example image, or code, thanks

<div>
          <ionic-selectable
            [(ngModel)]="country"
            [items]="countries"
            itemValueField="id"
            itemTextField="name"
            [canSearch]="true"
            placeholder="Search Country"
            (onSearch)="searchCountry($event)"
            isOnSearchEnabled="true">
          </ionic-selectable>
</div>

I solve my problem, I included ionic-selectable into a div as you see on the code above, and I just change it to an ion-item and it solves my problem.
