### ISSUE TITLE
Change the checkbox Icon depending on the platform

### ISSUE THREAD

**Issue by javebratt** [eakoriakin/ionic-selectable#214]
Hey there,

Is there a way to change the checkbox icon depending on the platform?

Like a regular ionic checkbox will be a square on Android and a circle on iOS, the ionic-selectable checkboxes are always circles.

Thanks!

**Comment by eakoriakin** [comment]
Hi, sure, have a look at the [ionicSelectableItemIconTemplate](https://github.com/eakoriakin/ionic-selectable/wiki#item-icon-template).

**Comment by javebratt** [comment]
Thank you! 😃
