### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by ralscha** [eakoriakin/ionic-selectable#215]
`ionic-selectable.component.ts` references `Renderer` which no longer exists in Angular 9.

https://github.com/eakoriakin/ionic-selectable/blob/master/src/app/components/ionic-selectable/ionic-selectable.component.ts#L2

Replacement is `Renderer2` which exists for quite some time. I think it has been introduced in Angular 4.

**Comment by edy-ap** [comment]
The issue is solved in #216. Will be integrated in the next release.
Thanks for you contribution.
