### ISSUE TITLE
Adding an image/flag to ionic_selectable in Ionic 4

### ISSUE THREAD

**Issue by mbelnf1** [eakoriakin/ionic-selectable#218]
Thank you very much for this package. I am having a problem adding an image to my selector. I am currently using the flag_icon_css package https://github.com/lipis/flag-icon-css to add the images.

When I add the flag image code inside the <ionic_selectable> it does not work but when I put it outside it works but with all the added flag images next to each other which I do not want and I want one flag per country

html page
```
                                        <ionic-selectable
                                          item-content
                                          [(ngModel)]="port"
                                          [items]="nations"
                                          itemTextField="country"
                                          
                                          [canSearch]="true"
                                          (onChange)="portChange($event)"                                        
                                          >
                                          <ion-item *ngFor="let c of nations">
                                              <ion-thumbnail slot="start">
                                                  <ng-container *ngIf="c.country"><ion-img src={{c.flag}}></ion-img></ng-container>
                                                </ion-thumbnail>
                                          </ion-item>
                                          </ionic-selectable>`
```
ts page
````
class countries {
  public country: string;
  public flag: any;
}

@Component({
.....
)}

export class page {
  nations: countries[]; 
  port: countries;  

constructor(){
this.nations = [
      {
        country: 'Afghanistan',
        flag: '/assets/Flags/4x3/af.svg'
      },
```
`

**Comment by zimejin** [comment]
I'm experiecing a similar issue. I know I can add one image by using the "ionicSelectableItemIconTemplate". But I can't figure out how to dynamically render avatars or unique icons per item in the selectable list.

**Comment by eakoriakin** [comment]
Yes, the proper way is to use "ionicSelectableItemIconTemplate" as described on the [wiki](https://github.com/eakoriakin/ionic-selectable/wiki). Here's the [demo](https://stackblitz.com/edit/ionic-selectable-item-icon-template?file=app/pages/home/home.html) as well.

Note how a current item and it's selected state are passed to the template - `let-port="item"`, `let-isPortSelected="isItemSelected"`, which can be used to configure the icon based on the item.

```
<ionic-selectable>
  <ng-template ionicSelectableItemIconTemplate let-port="item"
    let-isPortSelected="isItemSelected">
    <ion-icon
      [name]="isPortSelected ? 'checkmark-circle' : 'radio-button-off'"
      [color]="isPortSelected ? 'primary' : null">
    </ion-icon>
  </ng-template>
</ionic-selectable>
```

**Comment by mbelnf1** [comment]
> Yes, the proper way is to use "ionicSelectableItemIconTemplate" as described on the [wiki](https://github.com/eakoriakin/ionic-selectable/wiki). Here's the [demo](https://stackblitz.com/edit/ionic-selectable-item-icon-template?file=app/pages/home/home.html) as well.
> 
> Note how a current item and it's selected state are passed to the template - `let-port="item"`, `let-isPortSelected="isItemSelected"`, which can be used to configure the icon based on the item.
> 
> ```
> <ionic-selectable>
>   <ng-template ionicSelectableItemIconTemplate let-port="item"
>     let-isPortSelected="isItemSelected">
>     <ion-icon
>       [name]="isPortSelected ? 'checkmark-circle' : 'radio-button-off'"
>       [color]="isPortSelected ? 'primary' : null">
>     </ion-icon>
>   </ng-template>
> </ionic-selectable>
> ```

Can I use it with <ion-img>? Do I also need to create a service like the demo or can I use it directly from the page.ts?
