### ISSUE TITLE
No infinite scroll with virtual scroll

### ISSUE THREAD

**Issue by sapabg** [eakoriakin/ionic-selectable#220]
Infinite scroll does not trigger when virtual scroll is enabled.
"ionic-selectable": "^4.4.1", 
"@ionic-native/core": "^5.0.0",
"@ionic-native/splash-screen": "^5.0.0",
"@ionic-native/status-bar": "^5.0.0",
"@ionic/angular": "^4.7.1",

<ionic-selectable
              formControlName="patient"                   
              item-content
              [items]="patients"
              itemValueField="id"
              itemTextField="fullName"
              [canSearch]="true"
              searchPlaceholder="Намери пациент..."
              [shouldFocusSearchbar]="true"
              closeButtonText="Отказ"
              closeButtonSlot="primary"
              (onSearch)="onSearchPatients($event)"
              [hasInfiniteScroll]="true"
              (onInfiniteScroll)="onGetMorePatients($event)">

works but when I add
[hasVirtualScroll]="true"
virtualScrollApproxItemHeight="48px"
the onGetMorePatients does not trigger.

**Comment by edy-ap** [comment]
can you show an example in stackblitz?, please

**Comment by sapabg** [comment]
https://stackblitz.com/edit/ionic-selectable-infinite-scroll?file=pages%2Fhome%2Fhome.html

You can use the original examples, just add 
[hasVirtualScroll]="true"
virtualScrollApproxItemHeight="48px"
and you will see it.
I think I even found somewhere in the code a check that disables infinite scroll id virtual scroll is enabled. I have implemented both infinite and virtual scroll on the same list so I know it works. I think it is intentionally disabled in this case.

**Comment by edy-ap** [comment]
thanks ,i will ckeck the code

**Comment by sapabg** [comment]
> thanks ,i will ckeck the code

**Comment by sapabg** [comment]
Is there hope for this being fixed?
I updated to 4.6.0 still the same...
