### ISSUE TITLE
Backdrop close not working

### ISSUE THREAD

**Issue by newnewtmailcom** [eakoriakin/ionic-selectable#221]
<ionic-selectable
    [(ngModel)]="val"
    [items]="items"
    itemValueField="value"
    itemTextField="name"
    [canSearch]="true"
    closeButtonSlot="end"
    [shouldBackdropClose]="true"
    (onChange)="Change($event)"
    ></ionic-selectable>
-----------------------------------
ionic -v is : 5.4.2;
node -v is : 10.16.0;
npm -v is:6.11.3
-----------------------------------
"ionic-selectable": "^4.4.1",
-----------------------------------
When i press back button in android naugat, component model is not closing, this event is perform in background pages.

**Comment by edy-ap** [comment]
can you show an example in stackblitz?, please
