### ISSUE TITLE
Cannot open component due to modal controller parameters incorrect parsing

### ISSUE THREAD

**Issue by eugenebovkun** [eakoriakin/ionic-selectable#223]
Hi Evgeniy. Thanks a lot for powerful component, I found a lot of useful demo cases.

Unfortunately, I am not able to use this component in my app.
Input is shown, but when I click to show modal error is caused. 

`core.js:9110 ERROR Error: Uncaught (in promise): TypeError: modal.onWillDismiss is not a function
TypeError: modal.onWillDismiss is not a function
    at ionic-selectable.component.js:1665
    at ZoneDelegate.invoke (zone-evergreen.js:359)`

`core.js:9110 ERROR Error: Uncaught (in promise): TypeError: Cannot set property '_modalComponent' of undefined
TypeError: Cannot set property '_modalComponent' of undefined
    at new IonicSelectableModalComponent (ionic-selectable-modal.component.js:17)
    at createClass (core.js:27867)`

as I found porblem is this.selectComponent = this.navParams.get('selectComponent'); set value as undefined (ionic-selectable-modal.component.js:16)

I am trying to use the most generic example.

`<div *ngIf="showBreedList">`
`    <ion-item>`
`        <ion-label>Select</ion-label>`
`        <ionic-selectable`
`             [(ngModel)]="breed"`
`             itemValueField="id"`
`             itemTextField="name"`
`             [items]="breeds"`
`             [canSearch]="true"`
`             (onChange)="selectBreed($event)">`
`        </ionic-selectable>`
`    </ion-item>`
`</div>`

This is the list of my dependencies: 
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/fire": "^5.2.1",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@capacitor/core": "^1.2.0",
    "@ionic-native/core": "^5.18.0",
    "@ionic-native/splash-screen": "^5.18.0",
    "@ionic-native/status-bar": "^5.18.0",
    "@ionic/angular": "^4.11.7",
    "@mobiscroll/angular-lite": "^4.8.1",
    "@ngx-formly/core": "^5.5.6",
    "@ngx-formly/ionic": "^5.5.0",
    "core-js": "^2.5.4",
    "cors": "^2.8.5",
    "fetch-cookie": "^0.7.3",
    "firebase": "^6.6.2",
    "ionic-selectable": "^4.5.1",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"

I would be grateful for your help because spend a few hours to find any receipt on the Internet without any success. 

Thanks in advanced
Ievgen.

**Comment by eakoriakin** [comment]
Hey, can you replicate it on Stackblitz?

**Comment by edy-ap** [comment]
Hi eugenebovkun. 
I am reviewing your problem. Using navparams you cannot pass components, just string or json string objects.

**Comment by edy-ap** [comment]
it´s not a bug
