### ISSUE TITLE
Error: Uncaught (in promise): IonicSelectable is disabled or already closed.

### ISSUE THREAD

**Issue by am-katrin** [eakoriakin/ionic-selectable#228]
On Android I have the issue, that this error is thrown.

How to reproduce:
1) Open ionic-selectable (multiselect=false)
2) select value, 
3) press a lot during close animation.

We got a lot of error reports form our users with this crash :(

any suggestions how to solve this ?

**Comment by edy-ap** [comment]
can you show an example?(i.e stackblitz)
