### ISSUE TITLE
Default Value

### ISSUE THREAD

**Issue by tirathpal** [eakoriakin/ionic-selectable#233]
How can i place default selected value.

**Comment by eakoriakin** [comment]
If you use `[(ngModel)]="port"` then initialize the value in your class, e.g.

```
class PortsPage {
  port: Port = { id: 1, name: 'Amsterdam' };
}
```

If you make use of Reactive Forms then set the value of the `[formControl]="portFormControl"`:

```
class PortsPage {
  portFormControl: FormControl = new FormControl({ id: 1, name: 'Amsterdam' });
}
```
