### ISSUE TITLE
Angular 9

### ISSUE THREAD

**Issue by khain2007** [eakoriakin/ionic-selectable#234]
When I try to upgrade from Angular 8 to 9, I get the following error: Package "ionic-selectable" has an incompatible peer dependency to "zone.js" (requires "~0.9.1", would install "0.10.2").

**Comment by pedronieto84** [comment]
Same error I get, when will be ready next version?

**Comment by edy-ap** [comment]
thanks, it fixed in release 4.7.0, is now available on npm
