### ISSUE TITLE
ionicSelectableAddItemTemplate not showing on Iphone

### ISSUE THREAD

**Issue by Edmundoacosta** [eakoriakin/ionic-selectable#241]
Hi everybody

When i press the button to open the AddItemTemplate nothing happens on my iphone device, just the buttons at the footer. but on android or ionic lab everything works fine.

![example_1](https://user-images.githubusercontent.com/18452793/75806719-379da080-5d52-11ea-9b36-7f3c7ba587d5.png)

![example?2](https://user-images.githubusercontent.com/18452793/75807032-b4c91580-5d52-11ea-8329-c4da5939a37b.png)

```
ionic 4.17.0
angular 5.0.3
```

**Comment by edy-ap** [comment]
Thanks for the issue. Can you provide a repo with the code required to reproduce this issue?. it´s only happens on devices?
