### ISSUE TITLE
An accessor cannot be declared in an ambient context

### ISSUE THREAD

**Issue by manisi** [eakoriakin/ionic-selectable#252]
ERROR in node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable-modal.component.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

Ionic:
   Ionic CLI                     : 6.3.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Utility:
  cordova-res : not installed
   native-run  : 0.3.0

System:
   NodeJS : v13.7.0 (/usr/local/Cellar/node/13.7.0/bin/node)
   npm    : 6.14.2
   OS     : macOS Catalina

**Comment by manisi** [comment]
// Ionic 4
npm install ionic-selectable@4.5.0 --save

fixed with this version

**Comment by gelinger777** [comment]
when you plan to fix this with higher versions?
