### ISSUE TITLE
Renderer issue on Angular 9

### ISSUE THREAD

**Issue by 12021341** [eakoriakin/ionic-selectable#253]
I'm getting an issue of "export 'Renderer' was not found in '@angular/core' on angular 9? 
Seems Renderer is deprecated and totally removed on angular 9. It suggest to use Renderer2

**Comment by edy-ap** [comment]
what version you use?

**Comment by JeongJun-Lee** [comment]
same here from 4.5.0

**Comment by JeongJun-Lee** [comment]
But 4.7.1 version looks like being ready to Angular 9. Install it:

npm i ionic-selectable@4

**Comment by edy-ap** [comment]
is your problem solved?

**Comment by 12021341** [comment]
Yes thanks!
