### ISSUE TITLE
error TS1086: An accessor cannot be declared in an ambient context

### ISSUE THREAD

**Issue by gencharitaci** [eakoriakin/ionic-selectable#256]
I'm facing this issue, how can I solve this problem. I tried to downgrade Typescript version. But didn't solve

error TS1086:

Node version: 13.11.0
Angular CLI version: 8.3.26
Typescript version: 3.4.3
Ionic version: 6.4.0
Ionic-selectable version 4.7.0

> ng.cmd run app:serve --host=localhost --port=8100
[ng] i ｢wds｣: Project is running at http://localhost:8100/webpack-dev-server/
[ng] i ｢wds｣: webpack output is served from /
[ng] i ｢wds｣: 404s will fallback to //index.html
[ng] chunk {main} main.js, main.js.map (main) 2 kB [initial] [rendered]
[ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 154 kB [initial] [rendered]
[ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
[ng] chunk {styles} styles.js, styles.js.map (styles) 118 kB [initial] [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 340 kB [initial] [rendered]
[ng]
[ng] ERROR in node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable-modal.component.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 13     get _canClearCssClass(): boolean;
[ng]            ~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable-modal.component.d.ts:14:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 14     get _isMultipleCssClass(): boolean;
[ng]            ~~~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable-modal.component.d.ts:15:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 15     get _isSearchingCssClass(): boolean;
[ng]            ~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable-modal.component.d.ts:16:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 16     get _isIos(): boolean;
[ng]            ~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable-modal.component.d.ts:18:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 18     get _isAddItemTemplateVisibleCssClass(): boolean;
[ng]            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:16:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 16     get _isMultipleCssClass(): boolean;
[ng]            ~~~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:17:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 17     get _hasValueCssClass(): boolean;
[ng]            ~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:18:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 18     get _hasPlaceholderCssClass(): boolean;
[ng]            ~~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:19:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 19     get _hasIonLabelCssClass(): boolean;
[ng]            ~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:20:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 20     get _hasDefaultIonLabelCssClass(): boolean;
[ng]            ~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:21:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 21     get _hasFixedIonLabelCssClass(): boolean;
[ng]            ~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:22:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 22     get _hasStackedIonLabelCssClass(): boolean;
[ng]            ~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:23:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 23     get _hasFloatingIonLabelCssClass(): boolean;
[ng]            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:44:17 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 44     private get _hasInfiniteScroll();
[ng]                    ~~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:45:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 45     get _shouldStoreItemValue(): boolean;
[ng]            ~~~~~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:70:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 70     get label(): string;
[ng]            ~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:79:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 79     get searchText(): string;
[ng]            ~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:80:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 80     set searchText(searchText: string);
[ng]            ~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:89:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 89     get isSearching(): boolean;
[ng]            ~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:98:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 98     get hasSearchText(): boolean;
[ng]            ~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:99:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 99     get value(): any;
[ng]            ~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:100:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 100     set value(value: any);
[ng]             ~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:117:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 117     get isEnabled(): boolean;
[ng]             ~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:118:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 118     set isEnabled(isEnabled: boolean);
[ng]             ~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:126:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 126     get shouldBackdropClose(): boolean;
[ng]             ~~~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:127:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 127     set shouldBackdropClose(shouldBackdropClose: boolean);
[ng]             ~~~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:160:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 160     get isOpened(): boolean;
[ng]             ~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:178:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 178     get hasConfirmButton(): boolean;
[ng]             ~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:179:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 179     set hasConfirmButton(hasConfirmButton: boolean);
[ng]             ~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:232:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 232     get isOnSearchEnabled(): boolean;
[ng]             ~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:233:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 233     set isOnSearchEnabled(isOnSearchEnabled: boolean);
[ng]             ~~~~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:241:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 241     get canClear(): boolean;
[ng]             ~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:242:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 242     set canClear(canClear: boolean);
[ng]             ~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:292:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 292     get isMultiple(): boolean;
[ng]             ~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:293:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 293     set isMultiple(isMultiple: boolean);
[ng]             ~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:475:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 475     get itemsToConfirm(): any[];
[ng]             ~~~~~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:524:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 524     get canAddItem(): boolean;
[ng]             ~~~~~~~~~~
[ng] node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:525:9 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 525     set canAddItem(canAddItem: boolean);
[ng]             ~~~~~~~~~~
[ng]
[ng] Date: 2020-04-05T13:08:09.743Z - Hash: a2f6e144c556d00fb0c5 - Time: 6884ms
[ng] i ｢wdm｣: Failed to compile.

**Comment by gencharitaci** [comment]
I upgraded to Angular 9 and its fixed. Followed instructions: https://update.angular.io/#8.0:9.0l3

**Comment by shabbir-dhangot** [comment]
is it only solution? @gencharitaci

**Comment by gencharitaci** [comment]
> is it only solution? @gencharitaci

I followed upgrade and migration directions on that page: https://update.angular.io/#8.0:9.0l3 and it worked well for me.
