### ISSUE TITLE
Is there good example with items translated by ngx-translate?

### ISSUE THREAD

**Issue by JeongJun-Lee** [eakoriakin/ionic-selectable#258]
I want to support multi languages by https://github.com/ngx-translate/core.
Is there good example with items translated by ngx-translate? Just not with label and button.

<ion-label>{{'Store.StoreType' | translate}}</ion-label>
        <ionic-selectable
          formControlName="storeType"
          [items]="storeTypes"
          itemValueField="id"
          itemTextField="name"
          closeButtonText={{'Common.Close' | translate}}>
        </ionic-selectable>

**Comment by terranmarine** [comment]
Hi @JeongJun-Lee, 

I am using ngx-translate in my app and the selectable component. Below you can see my implementation. You can use `ng-template` to su==customize the rendered information. There might be better solution ofc, but the following example is working for us.

`<ion-item class="field-wrapper" lines="full" mode="md" button>
    <ion-label class="form-field-label" mode="md">
        <ion-icon name="clipboard" class="form-input-icon"></ion-icon>
        {{ labelContent }}
    </ion-label>
    <ionic-selectable
        item-content
        #products
        class="products-selectable"
        [items]="allProducts"
        [isMultiple]="true"
        itemValueField="id"
        itemTextField="name"
        groupValueField="group_name"
        groupTextField="group_name"
        searchPlaceholder="{{ 'FORM.SEARCH_PRODUCTS' | translate }}"
        [canSearch]="true"
        [searchDebounce]="1500"
        (onSelect)="onProductSelect($event)"
        (onSearch)="onSearchProducts($event)"
        (onClose)="onModalClose($event)"
        (onOpen)="onModalOpen($event)"
        [hasInfiniteScroll]="true"
        (onInfiniteScroll)="loadMoreProductData($event)"
    >
        <ng-template ionicSelectableHeaderTemplate>
            <ion-title mode="md" class="title-products">
                <span class="cancel-products" (click)="productsComponent.close()">
                    {{ 'SHARED.CANCEL' | translate }}
                </span>
                <span class="title_text">
                    {{ 'FORM.PRODUCTS_HEADER' | translate }}
                </span>
                <ion-icon
                    (click)="startScanner($event)"
                    name="barcode"
                    class="icon-barcode"
                ></ion-icon>
            </ion-title>
        </ng-template>
        <ng-template ionicSelectableGroupTemplate let-group="group">
            <div style="width: 100%">
                <ion-item
                    *ngIf="allow_employees_to_add_new_products &&
                        basicProductsPagination.count === 0"
                    class="ion-text-center"
                    lines="full"
                    button
                    mode="md"
                    (click)="createProduct()"
                >
                    <ion-label class="add-item-txt">
                        {{ 'FORM.CREATE_PRODUCT' | translate }} {{ searchString }}
                    </ion-label>
                    <ion-label class="add-icon-wrapper">
                        <ion-icon name="add-circle-outline" class="add-icon"></ion-icon>
                    </ion-label>
                </ion-item>
                <ion-item lines="none">
                    {{ group.text }}
                </ion-item>
            </div>
        </ng-template>
        <ng-template ionicSelectableSearchFailTemplate>
            <ion-item lines="full" class="ion-text-center" mode="md">
                <ion-label>{{ 'FORM.NO_PRODUCTS_FOUND' | translate }}</ion-label>
            </ion-item>
            <ion-item
                *ngIf="allow_employees_to_add_new_products"
                class="ion-text-center"
                lines="full"
                button
                mode="md"
                (click)="createProduct()"
            >
                <ion-label class="add-item-txt">
                    {{ 'FORM.CREATE_PRODUCT' | translate }} {{ searchString }}
                </ion-label>
                <ion-label class="add-icon-wrapper">
                    <ion-icon name="add-circle-outline" class="add-icon"></ion-icon>
                </ion-label>
            </ion-item>
        </ng-template>
        <ng-template ionicSelectableItemTemplate let-item="item">
            <div class="product-name-wrapper">
                <span>{{ item.name || item.text }}</span>
                <div *ngIf="show_selling_price_app" class="product-price">
                    <span *ngIf="item.selling_price % 1 === 0"
                        >{{ item.selling_price }}.00 + {{ 'FORM.VAT' | translate }}</span
                    >
                    <span *ngIf="item.selling_price % 1 !== 0"
                        >{{ item.selling_price }} + {{ 'FORM.VAT' | translate }}</span
                    >
                </div>
            </div>
        </ng-template>
    </ionic-selectable>`
