### ISSUE TITLE
What is the ideal version for Ionic 3

### ISSUE THREAD

**Issue by StephSince93** [eakoriakin/ionic-selectable#259]
For a long time I've had my ionic-selectable at 3.4.0, but I recently ran an update and it updated to 3.5.0. The Readme says to download 3.4.0, but it also states Ionic 3 (3.6.0 - 3.9.2). Not sure if I am okay with my current version or not.

**Comment by edy-ap** [comment]
for ionic 3 use ionic-selectable@3.5.0
