### ISSUE TITLE
How we can read or set a unique property of an object element in items array?

### ISSUE THREAD

**Issue by pagyx93** [eakoriakin/ionic-selectable#263]
Hi, thank you for this beautiful plugin, my question is represented in the below use case example
```
<ion-select [(ngModel)]="obj.ID">
 <ion-select-option *ngFor="let el of elements" [value]="el.ID">{{ el.Description }} </ion-select-option>
 </ion-select>
```

With ionic-selectable the ngModel can be used only with the entire object, but in this case may be extremely useful get/set a single property of object. I didn't find the way to do this. Any suggestions?
thanks in advice

**Comment by eakoriakin** [comment]
Hi, here you go https://github.com/eakoriakin/ionic-selectable/wiki#shouldstoreitemvalue
