### ISSUE TITLE
Problem in search string

### ISSUE THREAD

**Issue by onderturhan** [eakoriakin/ionic-selectable#265]
Hi,  when i search city in turkey with special character(ex:  "i", "ş"),it doesnt work. I attached this view
, could you help me?

![problem](https://user-images.githubusercontent.com/10496500/79558588-0f24f800-80ad-11ea-9909-e13b1c89cbc1.png)

**Comment by monurakkaya** [comment]
@onderturhan cozdun mu sorunu?
