### ISSUE TITLE
How do I modify the itemTextField label when an item is selected?

### ISSUE THREAD

**Issue by marcelo-ansaldi-baltazar** [eakoriakin/ionic-selectable#266]
Basically, i can't find the proper way to change the label of the selected item (yellow marked area)
![image](https://user-images.githubusercontent.com/26723811/79832456-7aa1ea80-8377-11ea-83a8-d8d1151cc886.png)

I'm using a template to show more data than just "itemTextField".

`
<ng-template ionicSelectableItemTemplate let-empleado="item">
        {{empleado.nombre}} {{empleado.apellido_pat}} {{empleado.apellido_mat}}
 </ng-template>
`

looks like this (instead of just "Marcelo")
![image](https://user-images.githubusercontent.com/26723811/79832653-e5532600-8377-11ea-840f-751903192a72.png)

I want to do kind of the same with the label i mentioned first. :(

**Comment by eakoriakin** [comment]
What you need is Value Template - https://github.com/eakoriakin/ionic-selectable/wiki#value-template
