### ISSUE TITLE
How to implement in ionic 5

### ISSUE THREAD

**Issue by EDcasa** [eakoriakin/ionic-selectable#278]
Example with ionic 5

**Comment by gabrielmtns** [comment]
Follow the docs.  so far worked fine for me

**Comment by edy-ap** [comment]
its same than v4.

**Comment by burdokat** [comment]
Same as v4

**Comment by EDcasa** [comment]
Not working for mr in ionic  @ionic/angular 5.1.1
this error:
Refused to load the image 'http://localhost:8100/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback
When install ionic-searchable@4.4.0

**Comment by 00william** [comment]
I had the same problem with `npm install ionic-selectable@4.5.0 --save`.

The Ionic info:

     Ionic:
     Ionic CLI                         : 6.9.1
     Ionic Framework                   : @ionic/angular 5.1.1
     @angular-devkit/build-angular     : 0.901.6
     @angular-devkit/schematics        : 9.1.6
     @angular/cli                      : 9.1.6
     @ionic/angular-toolkit            : 2.2.0

     Cordova:
     Cordova CLI                       : 9.0.0 (cordova-lib@9.0.1)
     Cordova Platforms                 : android 8.1.0
     Cordova Plugins                   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 8 other plugins)

     Utility:
     cordova-res                       : 0.14.0
     native-run                        : 1.0.0

     System:
     Android SDK Tools                 : 26.1.1
     NodeJS                            : v12.16.2
     npm                               : 6.14.5
     OS                                : Windows 10

Using `ionic cordova run android --device -l` the CMD showed:

     [ng] ERROR in node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:1:70 - error TS2724: Module '"../../../../../../../../../mobile_app/node_modules/@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?
     [ng] 1 import { DoCheck, ElementRef, EventEmitter, IterableDiffers, OnInit, Renderer, TemplateRef } from '@angular/core';
     [ng]                                                                        ~~~~~~~~
     [ng]   node_modules/@angular/core/core.d.ts:5764:31
     [ng]     5764 export declare abstract class Renderer2 {
     [ng]                                        ~~~~~~~~~
     [ng]     'Renderer2' is declared here.

Then I change all 'Renderer' to 'Renderer2' in node_modules\ionic-selectable\src\app\components\ionic-selectable\ionic-selectable.component.d.ts and \node_modules\ionic-selectable\__ivy_ngcc__\esm2015\src\app\components\ionic-selectable\ionic-selectable.component.js

This worked for me!

**Comment by subodhkvg** [comment]
> I had the same problem with `npm install ionic-selectable@4.5.0 --save`.
> 
> The Ionic info:
> 
> ```
>  Ionic:
>  Ionic CLI                         : 6.9.1
>  Ionic Framework                   : @ionic/angular 5.1.1
>  @angular-devkit/build-angular     : 0.901.6
>  @angular-devkit/schematics        : 9.1.6
>  @angular/cli                      : 9.1.6
>  @ionic/angular-toolkit            : 2.2.0
> 
>  Cordova:
>  Cordova CLI                       : 9.0.0 (cordova-lib@9.0.1)
>  Cordova Platforms                 : android 8.1.0
>  Cordova Plugins                   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 8 other plugins)
> 
>  Utility:
>  cordova-res                       : 0.14.0
>  native-run                        : 1.0.0
> 
>  System:
>  Android SDK Tools                 : 26.1.1
>  NodeJS                            : v12.16.2
>  npm                               : 6.14.5
>  OS                                : Windows 10
> ```
> 
> Using `ionic cordova run android --device -l` the CMD showed:
> 
> ```
>  [ng] ERROR in node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:1:70 - error TS2724: Module '"../../../../../../../../../mobile_app/node_modules/@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?
>  [ng] 1 import { DoCheck, ElementRef, EventEmitter, IterableDiffers, OnInit, Renderer, TemplateRef } from '@angular/core';
>  [ng]                                                                        ~~~~~~~~
>  [ng]   node_modules/@angular/core/core.d.ts:5764:31
>  [ng]     5764 export declare abstract class Renderer2 {
>  [ng]                                        ~~~~~~~~~
>  [ng]     'Renderer2' is declared here.
> ```
> 
> Then I change all 'Renderer' to 'Renderer2' in node_modules\ionic-selectable\src\app\components\ionic-selectable\ionic-selectable.component.d.ts and \node_modules\ionic-selectable__ivy_ngcc__\esm2015\src\app\components\ionic-selectable\ionic-selectable.component.js
> 
> Also you need to import `IonicSelectableModule` to each page module. visit https://github.com/eakoriakin/ionic-selectable/wiki#why-do-i-get-error-cant-bind-to-items-since-it-isnt-a-known-property-of-ionic-selectable
> 
> This worked for me!

Thanks !!...It's working for me as well

**Comment by ajasir** [comment]
> I had the same problem with `npm install ionic-selectable@4.5.0 --save`.
> 
> The Ionic info:
> 
> ```
>  Ionic:
>  Ionic CLI                         : 6.9.1
>  Ionic Framework                   : @ionic/angular 5.1.1
>  @angular-devkit/build-angular     : 0.901.6
>  @angular-devkit/schematics        : 9.1.6
>  @angular/cli                      : 9.1.6
>  @ionic/angular-toolkit            : 2.2.0
> 
>  Cordova:
>  Cordova CLI                       : 9.0.0 (cordova-lib@9.0.1)
>  Cordova Platforms                 : android 8.1.0
>  Cordova Plugins                   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 8 other plugins)
> 
>  Utility:
>  cordova-res                       : 0.14.0
>  native-run                        : 1.0.0
> 
>  System:
>  Android SDK Tools                 : 26.1.1
>  NodeJS                            : v12.16.2
>  npm                               : 6.14.5
>  OS                                : Windows 10
> ```
> 
> Using `ionic cordova run android --device -l` the CMD showed:
> 
> ```
>  [ng] ERROR in node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:1:70 - error TS2724: Module '"../../../../../../../../../mobile_app/node_modules/@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?
>  [ng] 1 import { DoCheck, ElementRef, EventEmitter, IterableDiffers, OnInit, Renderer, TemplateRef } from '@angular/core';
>  [ng]                                                                        ~~~~~~~~
>  [ng]   node_modules/@angular/core/core.d.ts:5764:31
>  [ng]     5764 export declare abstract class Renderer2 {
>  [ng]                                        ~~~~~~~~~
>  [ng]     'Renderer2' is declared here.
> ```
> 
> Then I change all 'Renderer' to 'Renderer2' in node_modules\ionic-selectable\src\app\components\ionic-selectable\ionic-selectable.component.d.ts and \node_modules\ionic-selectable__ivy_ngcc__\esm2015\src\app\components\ionic-selectable\ionic-selectable.component.js
> 
> Also you need to import `IonicSelectableModule` to each page module. visit https://github.com/eakoriakin/ionic-selectable/wiki#why-do-i-get-error-cant-bind-to-items-since-it-isnt-a-known-property-of-ionic-selectable



> Thanks
> This worked for me!
