### ISSUE TITLE
Multiple selection container height problem

### ISSUE THREAD

**Issue by ursedaniel** [eakoriakin/ionic-selectable#280]
Hi, if I use the multi selection attribute and I pick like 3+ more items the height of the select increases without limits. Is there any way how can I change it to the traditional ion-selector? (left input is the original ionic and the right one is ionic-selectable component made by you).
![Screenshot 2020-05-06 at 20 24 04](https://user-images.githubusercontent.com/17604236/81208524-db682e80-8fd7-11ea-9432-174fd7c1deda.png)

**Comment by ursedaniel** [comment]
Managed to do this workaround on selecting items
` portChange(event: {
        component: IonicSelectableComponent,
        value: any
    }) {
        if (event.value.length > 1) {
            setTimeout(() => {
                const nodesList = document.querySelectorAll('.ionic-selectable-value-item');
                if (nodesList[0].innerHTML.indexOf('.') === -1) {
                    nodesList[0].innerHTML = nodesList[0].innerHTML + '...';
                }
                for (let i = 1; i < nodesList.length; i++) {
                    nodesList[i].innerHTML = '';
                }
            }, 0);
        }
    }`

If you guys now a better solution please let me know.

**Comment by edy-ap** [comment]
you can use ionicSelectableValueTemplate for custom
