### ISSUE TITLE
Select dont display initial value

### ISSUE THREAD

**Issue by pasblin** [eakoriakin/ionic-selectable#287]
ionic-selectable don't show ngmodel initial value and when call hasValue returns false, but model data is loaded.

"ionic-selectable": "^4.7.1"
 "@angular/core": "^9.1.11",
 "@ionic-native/core": "^5.26.0",

**Comment by pasblin** [comment]
Hi,
any progress on this topic?

**Comment by eakoriakin** [comment]
Hi, provide a StackBlitz demo please with the reproducable error. Closing it until then.

**Comment by adamjhickey** [comment]
I managed to get this working by wrapping my detectChanges call in a setTimeout.

**Comment by pasblin** [comment]
thx @adamjhickey , it works
