### ISSUE TITLE
slow on loading 30000 data

### ISSUE THREAD

**Issue by anjalikarn** [eakoriakin/ionic-selectable#299]
Hello, i am using ionic selectable in my project and it is working fine but it is very slow in filtering data in 30000 data.
Is there anything to improve the speed and performance

**Comment by eakoriakin** [comment]
Hey, thanks for using IonicSelectable. There're a couple of things you can do:
https://github.com/eakoriakin/ionic-selectable/wiki#what-is-the-best-way-to-handle-a-large-amount-of-items

**Comment by anjalikarn** [comment]
I am already using asynchronous search then also it is taking so much time
