### ISSUE TITLE
Metadata version mismatch error

### ISSUE THREAD

**Issue by kimrohdin** [eakoriakin/ionic-selectable#3]
I'm able to build AOT with the latest ionic-select-searchable@1.0.9 but it throws error when using the searchable control:

ERROR Error: Uncaught (in promise): Error: No component factory found for t. Did you add it to @NgModule.entryComponents?
Error: No component factory found for t. Did you add it to @NgModule.entryComponents?

Working fine on regular serve

**Comment by eakoriakin** [comment]
Hey, how do you build it? Can you try using --release flag, instead of --prod?

**Comment by kimrohdin** [comment]
Hey - thanks for reply - yes, running only the --release flag works
running --release --prod gives the error when trying to use the select control

**Comment by eakoriakin** [comment]
Hey @kimrohdin, can you try `1.0.14` version? Let me know if it works for you.

**Comment by jessicastorm1986** [comment]
when trying to build --prod getting this error -Error: Metadata version mismatch for module F:/D/IONIC/quicktask/quicktask-20march/quicktask/node_modules/ionic-select-searchable/ionic-select-searchable.d.ts, found version 4, expected 3

**Comment by williampaulo** [comment]
I too, found version 4, expected 3

**Comment by mrsergejl** [comment]
I am getting the same error on build --prod


Here the details:

`cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : android 6.3.0 browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.8.0

System:

    ios-deploy : 1.9.2 
    Node       : v8.9.4
    npm        : 5.6.0 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro`



`{
  "name": "ionic3-angular4",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "config": {
    "ionic_webpack": "webpack.config.js"
  },
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "4.1.3",
    "@angular/cli": "^1.7.3",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/compiler-cli": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/platform-browser-dynamic": "~4.1.0",
    "@angular/tsc-wrapped": "^4.4.6",
    "@ionic-native/camera": "^4.5.3",
    "@ionic-native/core": "4.3.2",
    "@ionic-native/file-transfer": "^4.5.3",
    "@ionic-native/globalization": "^4.5.3",
    "@ionic-native/image-picker": "^4.5.3",
    "@ionic-native/paypal": "^4.5.3",
    "@ionic-native/splash-screen": "4.3.2",
    "@ionic-native/status-bar": "4.3.2",
    "@ionic-native/stripe": "^4.5.3",
    "@ionic/storage": "2.0.1",
    "@ngx-translate/core": "^7.2.2",
    "@ngx-translate/http-loader": "^0.1.0",
    "angular-l10n": "^3.5.1",
    "angular2-jwt": "^0.2.3",
    "body-parser": "^1.18.2",
    "card.io.cordova.mobilesdk": "^2.1.0",
    "com.paypal.cordova.mobilesdk": "^3.5.0",
    "cordova-android": "^6.4.0",
    "cordova-browser": "5.0.3",
    "cordova-custom-config": "^5.0.2",
    "cordova-ios": "~4.5.3",
    "cordova-plugin-camera": "^4.0.2",
    "cordova-plugin-device": "^1.1.7",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-globalization": "^1.0.9",
    "cordova-plugin-image-picker": "^1.1.3",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-splashscreen": "^4.1.0",
    "cordova-plugin-statusbar": "^2.4.1",
    "cordova-plugin-stripe": "^1.5.3",
    "cordova-plugin-whitelist": "^1.3.3",
    "cors": "^2.8.4",
    "express": "^4.16.3",
    "ionic-angular": "3.8.0",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionic-select-searchable": "^1.0.16",
    "ionic-tooltips": "^2.0.1",
    "ionicons": "3.0.0",
    "ng2-file-upload": "^1.3.0",
    "ngx-color-picker": "^4.5.3",
    "ngx-pagination": "^3.1.0",
    "rxjs": "^5.5.7",
    "stripe": "^5.5.0",
    "sw-toolbox": "3.6.0",
    "typescript": "^2.7.2",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.7",
    "@ngtools/webpack": "^1.10.2",
    "@plentymarkets/terra-components": "^2.1.46-zlk",
    "@types/interact.js": "^1.0.22",
    "@types/node": "^8.9.5",
    "@types/source-map": "^0.5.1",
    "@types/uglify-js": "^2.6.29",
    "@types/webpack": "^3.8.10",
    "bootstrap-loader": "^2.2.0",
    "css-loader": "^0.28.10",
    "html-loader": "^0.5.5",
    "sass-loader": "^6.0.7",
    "sass-resources-loader": "^1.3.3",
    "style-loader": "^0.20.3",
    "to-string-loader": "^1.1.5"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "ionic-plugin-keyboard": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-statusbar": {},
      "cordova-custom-config": {},
      "cordova-plugin-stripe": {},
      "cordova-plugin-globalization": {},
      "com.paypal.cordova.mobilesdk": {}
    },
    "platforms": [
      "ios",
      "android",
      "browser"
    ]
  }
}
`

**Comment by eakoriakin** [comment]
@mrsergejl, try this solution:
https://github.com/eakoriakin/ionic-select-searchable/issues/12#issuecomment-382639265

**Comment by natura4917** [comment]
I want a specific explanation.

**Comment by adrianoviana** [comment]
same error

any help?

**Comment by cambieri** [comment]
Same error here, and for us the workaround doesn't work.
Will you fix this soon? Otherwise this great component it's not usable in production.
Thanks.

**Comment by eakoriakin** [comment]
@cambieri can you prepare a small GitHub repo with this issue? Also, are you building for `Android` or `iOS`?

**Comment by eakoriakin** [comment]
@adrianoviana can you do the same - prepare a small GitHub repo with this issue? Also, are you building for Android or iOS?

**Comment by eakoriakin** [comment]
Hi @kodeine, can you share a repo where this issue can be reproduced, so I could help you?

**Comment by nikolajosipovic** [comment]
I wasn't able to figure out a solution for the "Metadata version mismatch for module.." error. 

Running Angular 4.4.4, ionic-angular 3.8.0.

Using the component from the sources worked as a temporary workaround. Will take a deeper look once I get a bit time. 

Btw, thanks for the great component!

**Comment by eakoriakin** [comment]
Hi @nikolajosipovic. thanks 🙂 
If you want you can also prepare a small repo, so I could use it to reproduce the error and help you fixing it.

**Comment by jeroenmaas** [comment]
I figured out a workaround. It's really nasty but maybe gives some clue where the issue is coming from:

in node_modules/ionic-select-searchable there is a file called: ionic-select-searchable.metadata.json. This is a json file that contains a rather interesting key called: 'version'. Changing that from 4 to 3 allows the project to be run.

https://registry.npmjs.org/ionic-select-searchable/-/ionic-select-searchable-2.5.0.tgz

Actually contains this metadata. Probably this package is compiled using a to new version compiler for our angular 4 projects.

**Comment by eakoriakin** [comment]
Hey @jeroenmaas, thanks man, this might help me to solve the issue 🙂

**Comment by RockettSally** [comment]
I had the same issue of "Metadata version mismatch error" and @jeroenmaas workaround suggestion worked fantastically!

Curiously when doing `"ionic serve"`,`"ionic cordova run"` or `"ionic cordova build"`, it went fine, without any errors, but when using `npm run build` it catches the error.

**Comment by hamdysdiri** [comment]
@RockettSally How did you import the module manually ?

**Comment by RockettSally** [comment]
@hamdysdiri Just add `SelectSearchableModule` into the `imports` of an NgModule (usually, the app.module.ts) and use it on the pages you want (don't forget to import it on app.module.ts)

**Comment by RedStarThrower** [comment]
I wanted to use this component for our application but will have to write my own, since I can't put it into production. Real pity, I hope you find a solution soon, as it's quite impressive!

**Comment by RedStarThrower** [comment]
This is a fantastic component! I really wish this error could be fixed, because I am unable to use it in production for our organization.

**Comment by eakoriakin** [comment]
Closed for inactivity.
