### ISSUE TITLE
Ionic 5 -  has no exported member 'Renderer'. Did you mean 'Renderer2'? 

### ISSUE THREAD

**Issue by amankkcc** [eakoriakin/ionic-selectable#303]
Hey there I'm trying to implement this in Ionic 5 app. And I'm getting the error ..

**ERROR in node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:1:70 - error TS2724: Module '"../../../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?**

Is there any way I can solve this issue and use it in Ionic 5. It also says..

 1 import { DoCheck, ElementRef, EventEmitter, IterableDiffers, OnInit, Renderer, TemplateRef } from '@angular/core';
[ng]                                                                            ~~~~~~~~
[ng]     
[ng]       node_modules/@angular/core/core.d.ts:5740:31
[ng]         5740 export declare abstract class Renderer2 {
[ng]                                            ~~~~~~~~~
[ng]         'Renderer2' is declared here.

**Comment by edy-ap** [comment]
what version of ionic-selectable is you use?

**Comment by henrylow97** [comment]
What I did to fix it was instead of running this command:
```
npm install ionic-selectable@4.5.0 --save // From their npm's page
```

Run this:
`npm install ionic-selectable --save`

This will install the latest one, which is around 4.7.x, then the "Rerender" error wont pop out anymore.
