### ISSUE TITLE
icon on function canDelete not working ionic 5

### ISSUE THREAD

**Issue by moraoscar** [eakoriakin/ionic-selectable#314]
Hello, I have been using this plugin for a long time and it is great, however, I am having a detail with the button to delete an item (specifically the md-trash icon, it is not rendering).

I am using the version:
"ionic-selectable": "^ 4.7.1",
"@ionic-native / core": "^ 5.0.0"

Please, if there is any solution I will be all eyes :)

And thanks for such a great plugin indeed

**Comment by ajasir** [comment]
Hello @moraoscar, 

Right click on ionic-selectable directory under node_modules in visual studio code. Click Reveal in Finder option (in Mac OS, In windows i believe it will be Open in Explorer or something. Or else you can directly go and open node modules directory located in your system). Then do a content search using the keyword **content:md-trash** 

This will list all the files which will have md-trash icons. Replace md-trash with ionic icon name such as trash or trash-sharp or trash-outline. 

Refresh your page and you will be able to see the icons.  If not, then restart the app and try again. 

Versions
----------
"@ionic-native/core": "^5.19.1",
"ionic-selectable": "^4.5.0",

![image](https://user-images.githubusercontent.com/1219474/96176001-5b140500-0f49-11eb-8693-9155e1b86b24.png)

**Comment by moraoscar** [comment]
Thanks so much, you are amazing :) 

De verdad gracias.
