### ISSUE TITLE
Ion-Selectable@4.5.0 Version Issue

### ISSUE THREAD

**Issue by Prabhu230818** [eakoriakin/ionic-selectable#316]
ERROR in node_modules/ionic-selectable/src/app/components/ionic-selectable/ionic-selectable.component.d.ts:1:70 - error TS2724: Module '"../../../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?
[ng] 1 import { DoCheck, ElementRef, EventEmitter, IterableDiffers, OnInit, Renderer, TemplateRef } from '@angular/core';
[ng]                                                                        ~~~~~~~~
[ng]   node_modules/@angular/core/core.d.ts:5929:31
[ng]     5929 export declare abstract class Renderer2 {
[ng]                                        ~~~~~~~~~
[ng]     'Renderer2' is declared here.

I'm using to Ionic version 6.1.19 and npm install ionic-selectable@4.5.0 --save

**Comment by glmdev** [comment]
I was experiencing this as well. It appears to be fixed in the latest version.

Remove the `ionic-selectable` from your package.json and do an `npm i --save ionic-selectable`.

**Comment by Prabhu230818** [comment]
Thanks glmdev it's working now
