### ISSUE TITLE
Just want a single value instead the whole object

### ISSUE THREAD

**Issue by Fab4guy** [eakoriakin/ionic-selectable#318]
In Select only the name of the item is displayed. This is also correct. But when I send the form, the ngModel will not only show the name but the whole item object. How can I only get access to the name of the item?

```
 <ion-item>
   <ion-label>Item</ion-label>
   <ionic-selectable
     name="lightItem_{{lightItem.id}}"
     [(ngModel)]="lightItem.item"
     [items]="items"
      itemValueField="name"
     itemTextField="name"
     [canSearch]="true">
   </ionic-selectable>
</ion-item>

export interface IItem {
  link: string;
  state: string;
  name: string;
  label: string;
}


```

![2020-12-03 23_36_49-Ionic App](https://user-images.githubusercontent.com/18136973/101096965-a4371b80-35c0-11eb-87eb-1a6610dd909c.png)

**Comment by edy-ap** [comment]
You can use https://github.com/eakoriakin/ionic-selectable/wiki#shouldstoreitemvalue
