### ISSUE TITLE
while installing it this error : Unexpected end of JSON input while parsing near '...3DGag=="

### ISSUE THREAD

**Issue by faisal-easi** [eakoriakin/ionic-selectable#322]

**Comment by edy-ap** [comment]
can you show an example?

**Comment by faisal-easi** [comment]
I've a mobile app with ionic + angular + django with latest version of all but with cordova as i'm not sure what causing this error
Unexpected end of JSON input while parsing near '...3DGag=="
npm ERR!     }
npm ERR!   }
npm ERR! }
npm ERR! '

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/etc/.npm/_logs/2021-01-06T10_55_16_313Z-debug.log

**Comment by faisal-easi** [comment]
okay i got it there was problem with the missing bracket in the package-lock.json file and thanks for the answer and the package.
