### ISSUE TITLE
Search does not change list while typing

### ISSUE THREAD

**Issue by fortunella** [eakoriakin/ionic-selectable#422]
After upgrading to v5.0.0 with Ionic 7 the list of items is not filtered during typing. The list is updated only when I leave the search box. This is a bit confusing.
With v4.9.0 and Ionic 6 the list changed after each keypress.

This is my code:
```
<ionic-selectable name="user" [(ngModel)]="selectedUser" [items]="usersList" [canSearch]="true" 
   [shouldFocusSearchbar]="true" [canClear]="true"
   clearButtonText="Logout" closeButtonSlot="end" (onChange)="checkSecurityCode()"
   itemValueField="value" itemTextField="label">
   <ng-template ionicSelectableCloseButtonTemplate>
      <ion-icon name="close-circle" style="font-size: 24px"></ion-icon>
   </ng-template>
</ionic-selectable>
```

**Comment by vc-rakesh** [comment]
Hi @fortunella 
Greetings for the day!

Thanks for raising an issue.
I have fixed the issue.

You can try out version 5.0.1

**Comment by fortunella** [comment]
Works perfect. Thank your very much.
