### ISSUE TITLE
All Html selectors for templates are broken in V5 (last version)

### ISSUE THREAD

**Issue by phyr0s** [eakoriakin/ionic-selectable#424]
All the template selectors are broken since v7 angular 16 update

For example ionicSelectableHeaderTemplate is not working

**Comment by vc-rakesh** [comment]
Hello @phyr0s 
Please make sure you have imported IonicSelectableHeaderTemplateDirective or relevant directive in your standalone component

**Comment by phyr0s** [comment]
hello @vc-rakesh  no one is exportable  Example--> IonicSelectableItemIconTemplateDirective  is not exportable. 

Package path ./src/app/components/ionic-selectable/ionic-selectable-item-icon-template.directive is not exported from package

**Comment by Anicspo** [comment]
I can confirm this...having the same issue

**Comment by vc-rakesh** [comment]
ok @phyr0s @Anicspo Thanks for confirming the issue. I will fix and update soon new release.

**Comment by Elwazeery** [comment]
It worked after importing the directive in the page module
`import { IonicSelectableComponent, IonicSelectableHeaderTemplateDirective } from 'ionic-selectable';
`
