### ISSUE TITLE
Module '"ionic-selectable"' has no exported member 'IonicSelectableModule'.

### ISSUE THREAD

**Issue by nx-irvin** [eakoriakin/ionic-selectable#429]
Hi! After upgrading to Ionic 7 / Angular 16, I'm getting the error:
Module '"ionic-selectable"' has no exported member 'IonicSelectableModule'.
I'm using ionic-selectable v5.0.2 and my proyect has no standalone components.

Is there any way to solve this? Thank you!

**Comment by iamkinetic** [comment]
I'm in the exact same situation.  Ionic 7, Angular 16, no standalone components and ionic-selectable seems to be broken.

**Comment by sergiosanabria** [comment]
I have the same problema updating ionic 6 to ionic 7

**Comment by irvjc82** [comment]
Apparently for Angular 16 and Ionic 7 you have to import the standalone component there is no more IonicSelectableModule.

`import { IonicSelectableComponent } from 'ionic-selectable';

@NgModule({
  imports: [
    IonicSelectableComponent
  ]
})
export class AppModule { }`

**Comment by sergiosanabria** [comment]
I upgraded Angular from 14 to 15 and it worked as @irvjc82  says. Thank you

**Comment by vc-rakesh** [comment]
Closing this because ionic-selectable v5.0.2 is only for standalone components and there is no more IonicSelectableModule
