### ISSUE TITLE
Unable to use ng-templates (ionic 7 / angular 16)

### ISSUE THREAD

**Issue by woutersteven2020** [eakoriakin/ionic-selectable#433]
Great job on the plug-in! Many useful features.

Using Ionic 7.3.2 and Angular 16.2.3 and v5 of Ionic-selectable.

<ng-templates> aren't working. None of them. The functionality itself, changing language is working fine. If I'm doing something wrong, it's eluding me.

```
    <ion-item>
        <ion-icon slot="start" name="globe-outline" size="large"></ion-icon>
        <ion-label>
            <h2>Language</h2>
            <p>Set the interface language</p>
        </ion-label>
        <ionic-selectable formControlName="language" [items]="languages" itemValueField="code"
            itemTextField="label" [canSearch]="false" (onChange)="changeLanguage($event)">

            <ng-template ionicSelectableTitleTemplate>
                Language <span style="color: gray;">(Test)</span>
            </ng-template>
        </ionic-selectable>
    </ion-item>
```

The template for the title, doesn't change the title. Also if i remove the <ion-label> .... </ion-label> there is no title being set. 

I also wasn't able to update individual item templates (for flag icons). I'm guessing it's the same reason.. Am i missing some property or doing something wrong?

**Comment by rezendeneto** [comment]
Same here and here's the versions I'm using in my project:

```
   Ionic Framework               : @ionic/angular 7.3.0
   @angular-devkit/build-angular : 16.2.0
   @angular-devkit/schematics    : 16.2.0
   @angular/cli                  : 16.2.0
   @ionic/angular-toolkit        : 9.0.0
```

**Comment by vc-rakesh** [comment]
@rezendeneto @woutersteven2020 You need to import `IonicSelectableTitleTemplateDirective` directive in your component to work correctly

**Comment by sciu** [comment]
> @rezendeneto @woutersteven2020 You need to import `IonicSelectableTitleTemplateDirective` directive in your component to work correctly

Dear Sir, could you show to me how to import directive in our component.
I already try it, but still not working.
All ng-template are not working.

Thks.

**Comment by rezendeneto** [comment]
@sciu have you tried something like this?
![image](https://github.com/eakoriakin/ionic-selectable/assets/607961/fcb52560-2b63-437a-a1c2-de7a7beb74e4)

**Comment by sciu** [comment]
@rezendeneto 
Thanks for ur help, it works...

I upgrade to ionic-selectable@5.0.3 then

at my page.module.ts :

import { IonicSelectableComponent, IonicSelectableAddItemTemplateDirective } from 'ionic-selectable';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    AccountPageRoutingModule,
    ReactiveFormsModule,
    IonicSelectableComponent,
    IonicSelectableAddItemTemplateDirective
  ],
  declarations: [AccountPage],
})

Hope it would help other.

**Comment by ZoltanKovacs02** [comment]
Here’s the full list of template directives you can import:

import {
  IonicSelectableComponent,
  IonicSelectableHeaderTemplateDirective,
  IonicSelectableFooterTemplateDirective,
  IonicSelectableTitleTemplateDirective,
  IonicSelectableItemTemplateDirective,
  IonicSelectableItemIconTemplateDirective,
  IonicSelectableGroupTemplateDirective,
  IonicSelectableSearchFailTemplateDirective,
  IonicSelectableCloseButtonTemplateDirective
} from 'ionic-selectable';

✅ How to use in your module
@NgModule({
  imports: [
    // other Angular/Ionic modules...
    IonicSelectableComponent,                     // always required
    IonicSelectableHeaderTemplateDirective,
    IonicSelectableFooterTemplateDirective,
    IonicSelectableTitleTemplateDirective,
    IonicSelectableItemTemplateDirective,
    IonicSelectableItemIconTemplateDirective,     // 👈 
    IonicSelectableGroupTemplateDirective,
    IonicSelectableSearchFailTemplateDirective,
    IonicSelectableCloseButtonTemplateDirective
  ],
  declarations: [
    // your components
  ]
})
export class YourModule {}
