### ISSUE TITLE
ionchange or (change)  is not dedicated

### ISSUE THREAD

**Issue by eligrifel** [eakoriakin/ionic-selectable#434]
it looks likes for some reason keyup or value change in text field dosent trigger sorting on the list 
only if loose focus or pressing enter then the list refresh and sort 
i think ionChange is not invoking any more on keyup maybe it has something to do with that

this is the part in the source code that dosent work 

 onChange: EventEmitter<{
        component: IonicSelectableComponent;
        value: any;
    }>;
    /**
     * Fires when the user is typing in Searchbar.
     * **Note**: `canSearch` and `isOnSearchEnabled` has to be enabled.
     * See more on [GitHub](https://github.com/eakoriakin/ionic-selectable/wiki/Documentation#onsearch).
     *

<ion-item   >
  <ionic-selectable  #adminClubList
  [(ngModel)]="selectedClub"
  [items]="this.clubsList"
  itemValueField="id"
  itemTextField="name"
  [canClear]="true"
  [canSearch]="true"
  (onChange)="clubSelected($event)"
 
  >
</ionic-selectable>
</ion-item>

**Comment by MSandeep111** [comment]
@eligrifel I was facing the same issue, I was using the 5.0.0 then I updated to version 5.0.2 and now its working fine.
Hope it helps.

**Comment by eligrifel** [comment]
It looks like  downgrade ionic package fix it .since they change the way to change works in updated version of ionic package 
Thank for the reply

**Comment by vc-rakesh** [comment]
As its working on latest version 5.0.2, I am closing this issue
