### ISSUE TITLE
Not working in device or emulator android

### ISSUE THREAD

**Issue by ITACC2018** [eakoriakin/ionic-selectable#54]
hy,,,,it run when i open throught the browser but not working when i run through emulator or device android?

**Comment by eakoriakin** [comment]
Hi, what error do you get?
Can you share a small repo with your issue so I could help you/

**Comment by ITACC2018** [comment]
when i click error

ERROR Error: Uncaught (in promise): Error: No component factory found for t. Did you add it to @NgModule.entryComponents?
Error: No component factory found for t. Did you add it to @NgModule.entryComponents?

**Comment by eakoriakin** [comment]
Hey, maybe you haven't imported component properly?
Have a look here:
https://github.com/eakoriakin/ionic-select-searchable#1-why-do-i-get-error-cant-bind-to-items-since-it-isnt-a-known-property-of-select-searchable

**Comment by ITACC2018** [comment]
still not working..i got error when i build apk and i installed in deviced
Error: No component factory found for t. Did you add it to @NgModule.entryComponents?

app.module.ts
import { NgModule, ErrorHandler } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { HttpModule } from '@angular/http';
import { Network } from '@ionic-native/network';
import { HttpClientModule } from "@angular/common/http";
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen'
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { MyApp } from './app.component';
import { IonicImageViewerModule } from 'ionic-img-viewer';
import { IonicImageLoader } from 'ionic-image-loader';
//import { FCM } from '@ionic-native/fcm';

import { SelectSearchableModule } from 'ionic-select-searchable';

@NgModule({
  declarations: [
		MyApp
  ],
  imports: [
		BrowserModule,
		HttpModule,
		HttpClientModule,
		LinkyModule,
		MomentModule,
		ComponentsModule,
		IonicModule.forRoot(MyApp, {
			iconMode: 'ios',
			modalEnter: 'modal-slide-in',
			modalLeave: 'modal-slide-out',
			tabsPlacement: 'bottom',
			pageTransition: 'ios-transition'
		}),
		AngularFireModule.initializeApp(firebaseConfig),
		AngularFireDatabaseModule,
		AngularFireAuthModule,
		ChatModule,
		AboutPageModule,
		SelectSearchableModule,
		IonicImageViewerModule,
		IonicImageLoader.forRoot()
  ],
  bootstrap: [IonicApp],
  entryComponents: [
		MyApp
  ],
  providers: [
		StatusBar,
		SplashScreen,
		AuthServiceProvider,
		{provide: ErrorHandler, useClass: IonicErrorHandler},
		AuthServiceProvider,
		EmojiProvider,
		BotmanProvider,
		CoaKategoriProvider,
		ToastService,
		Network,
		HelpCategoryProvider,
		BlogsBlogsProvider,
		GhostProvider
		//FCM
  ]
})
export class AppModule {}

and i imported in 

import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { AboutPage} from './about';
import { SelectSearchableModule } from 'ionic-select-searchable';

@NgModule({
    declarations: [AboutPage],
    imports: [
        IonicPageModule.forChild(AboutPage),
        SelectSearchableModule
    ],
})
export class AboutPageModule { }

please help me

**Comment by eakoriakin** [comment]
Can you share a project/repo with this error?

**Comment by ITACC2018** [comment]
sure,, this my repo
https://github.com/ITACC2018/itcaremobile

**Comment by eakoriakin** [comment]
Good, I'll have a look

**Comment by eakoriakin** [comment]
Install the latest version [2.4.0](https://github.com/eakoriakin/ionic-select-searchable/releases/tag/2.4.0).
Also, there were some breaking changes in versions above 1.0.0. Follow the below instructions to update:
- Update to [2.3.0](https://github.com/eakoriakin/ionic-select-searchable/releases/tag/2.3.0)
- Update to [2.1.1](https://github.com/eakoriakin/ionic-select-searchable/releases/tag/2.1.1)

**Comment by ITACC2018** [comment]
**woow thanks you so much..you save my life** 
:+1: :+1: :bear: :bear:

**Comment by eakoriakin** [comment]
@ITACC2018 don't forget to star the project 🙂 and let your friends know about it 👍

**Comment by prescindivel** [comment]
I have a similar problem in the version `2.10.0`.

```
ERROR Error: Uncaught (in promise): Error: No component factory found for SelectSearchablePageComponent. Did you add it to @NgModule.entryComponents?
Error: No component factory found for SelectSearchablePageComponent. Did you add it to @NgModule.entryComponents?
```

I'm using lazyload on pages like:

![image](https://user-images.githubusercontent.com/6462673/44675079-cf0b9000-aa05-11e8-9905-fbf5fd5ebac4.png)

![image](https://user-images.githubusercontent.com/6462673/44675133-fc583e00-aa05-11e8-90de-1f46b6222acd.png)

**Comment by prescindivel** [comment]
I just imported `SelectSearchableModule` see:

![image](https://user-images.githubusercontent.com/6462673/44693790-81604900-aa40-11e8-9786-ef388f59d3fd.png)

and the following error occurs:
```
ERROR Error: Uncaught (in promise): Error: No component factory found for SelectSearchablePageComponent. Did you add it to @NgModule.entryComponents?
```
Thank you for your help!

**Comment by lilianfelismino** [comment]
Hi there! I work with @prescindivel and we are trying to use this component on a lazyload page. Have you ever tryied to use it like we are trying to? Does it work that way?
Thanks in advance.

**Comment by CoreyReynolds** [comment]
I have a LL project lilanfelismino, worked for me same as any other.

**Comment by lilianfelismino** [comment]
Hey there, @CoreyReynolds! What version are you using? We are trying with version 2.10.0 of the ionic-selectable component + ionic 3 and it's not working.. :(  Is there a possibility of sharing your LL project, or maybe by seeing our code above, to give us some ideas of what would we do to make it work?

**Comment by CoreyReynolds** [comment]
Unfortunately it's not solely my project and I'm unable to host it for you to view, but if you're getting a specific error please share it.

**Comment by lilianfelismino** [comment]
As you can see above, as @prescindivel already shared it,  we are getting this error: 

ERROR Error: Uncaught (in promise): Error: No component factory found for SelectSearchablePageComponent. Did you add it to @NgModule.entryComponents?

Any ideas?
Thank you.

**Comment by CoreyReynolds** [comment]
Missed the connection between you two.
I'm looking at my project and I haven't done anything different:
`import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { SignaturePage } from './signature';
import { SelectSearchableModule } from 'ionic-select-searchable';
import { SignaturePadModule } from 'angular2-signaturepad';

@NgModule({
  declarations: [
    SignaturePage,
  ],
  imports: [
    IonicPageModule.forChild(SignaturePage),
    SelectSearchableModule,
    SignaturePadModule
  ],
})
export class SignaturePageModule {}
`


Sometimes ionic errors can be a bit indirect. Is it possibly referencing a different page/module?

**Comment by prescindivel** [comment]
Hi guys, I did both tests to confirm if the problem really is with the lazy load.

I had the same error with the lazy load:
```console
Error: No component factory found for SelectSearchablePageComponent. Did you add it to @NgModule.entryComponents?
```
I created a repository with two projects, one normal and another lazyload: https://github.com/prescindivel/ionic-selectable-test

@CoreyReynolds which version of the ionic-selectable do you use?

**Comment by CoreyReynolds** [comment]
Just went on vacation, so I’m not going to be much help, but I’m pretty sure the latest.

**Comment by lilianfelismino** [comment]
Hey there, @eakoriakin! Any idea? Could you help us, please?


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remetente
notificado por
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
31/08/18
08:50:25

Em qui, 30 de ago de 2018 às 10:02, CoreyReynolds <notifications@github.com>
escreveu:

**Comment by eakoriakin** [comment]
Hey guys, I’m on vacation now. I’ll try to help you when I’m back in a week or two

**Comment by eakoriakin** [comment]
This seems like a stale issue. New versions 3.3.0 and 4.3.0 have been release since then.
