### ISSUE TITLE
How to bring up keyboard on iOS?

### ISSUE THREAD

**Issue by 2426021684** [eakoriakin/ionic-selectable#71]
I have [focusSearchbar]=“true”. The search bar focuses in chrome but on iOS it does not. I am using the ionic DevApp.

**Comment by eakoriakin** [comment]
Hey, I’ll check it

**Comment by mikaelboff** [comment]
Any updates on this @eakoriakin

**Comment by eakoriakin** [comment]
Not yet, I’ve been rather busy. I’d appreciate it if you could clone the repo, run it in development and investigate...

**Comment by mikaelboff** [comment]
Sure, I will !

**Comment by eakoriakin** [comment]
@mikaelboff thanks mate 👍

**Comment by eakoriakin** [comment]
Closed for inactivity.
