### ISSUE TITLE
Help upgrading to ionic 4

### ISSUE THREAD

**Issue by rathodkaran07** [eakoriakin/ionic-selectable#72]
Hi,

Can you help me upgrade this plugin to ionic v4. I know its to early but I am trying to work with v4 so can you please guide me?

**Comment by eakoriakin** [comment]
Hey, I’ll have a look. Have you tried it already with v4, any errors?

**Comment by rathodkaran07** [comment]
Hi, 
Thanx for your prompt response.

First issues I was facing was related to package, so changed "ionic-angular" to "@ionic/angular"
Second issues was with Form, it says "Module has no exported member Form"
Third issues was with ViewController, it says "Module has no exported member ViewController"

So I have stopped here, can you help with where will I find these new moduels?

**Comment by edy-ap** [comment]
is breaking whit ionic v4.
we need to rewrite all the code

**Comment by edy-ap** [comment]
I propose to create a branch for ionic v4

**Comment by eakoriakin** [comment]
@edy-ap, yep, that's the plan 🙂

**Comment by rathodkaran07** [comment]
Hey @eakoriakin ,
Any update?

**Comment by eakoriakin** [comment]
Hey @rathodkaran07, sorry I was busy with other issues and work... Now I'm going on vacation for a couple of weeks, so I guess I only be able to start this in September.

**Comment by edy-ap** [comment]
i can help to dev

**Comment by eakoriakin** [comment]
Hey guys, `ionic-selectable` is now available for `Ionic >=4.0.0-beta.11`.

**Comment by FireSol** [comment]
That is awesome news, going to try it out this week….thanks
