### ISSUE TITLE
issue with ionic-select-searchable

### ISSUE THREAD

**Issue by dimalahbal** [eakoriakin/ionic-selectable#80]
when i try to implement module ionic-select-searchable in my code , the page.html doesn't recognise select-searchable, i follow the same steps as described in documentation and  in the video youtube .. but i don't know what's the issue

**Comment by eakoriakin** [comment]
Hey, what video did you follow?

**Comment by dimalahbal** [comment]
This one of simon grimm : 
   https://youtu.be/pHuhokaLc-c

**Comment by eakoriakin** [comment]
Wow, there's a video out there... I had no idea 🙂 
Anyways, have a look a this demo, it might help to solve your issue:
https://stackblitz.com/edit/ionic-select-searchable-basic?file=pages%2Fhome%2Fhome.html

**Comment by eakoriakin** [comment]
Closed for inactivity.

**Comment by dimalahbal** [comment]
I'm sorry to be late on response .. i was busy ... The module is not working with ionic serve .. it's working only on emulator or device

**Comment by eakoriakin** [comment]
Hey, can you share your code?

**Comment by dimalahbal** [comment]
sorry  to be late on you ... here is my code : 

page.html

`<ion-content padding>

  <ion-item>
      <ion-label>Selectionner votre ville</ion-label>
      <select-searchable
        item-content
        [(ngModel)]="villeslctd"
        [items]="villes"
        itemValueField="id"
        itemTextField="nom"
        [canSearch]="true"
        (onChange)="villeChanged($event)"
        >
      </select-searchable>

  </ion-item>

  <div>

    <button (click)="valider()" class=" uk-button-danger uk-width-1-1 " >
        <div> Valider </div>
    </button>

  </div>

</ion-content>`

page.ts 

`
getVilles(){

  return this.dat.getVille().then( data => {

    this.villes = data;


  });

}

villeChanged( event : {component : SelectSearchableComponent , value : any}){

  this.ville =  this.villeslctd.nom ;
  this.id_ville =  this.villeslctd.id ;
  console.log('event :' , event);
  console.log('ville selected : ' + this.ville);
  console.log('id_ville selected : ' + this.villeslctd.id);


}
`

**Comment by eakoriakin** [comment]
Do you get any errors?

**Comment by dimalahbal** [comment]
on the device i get no errors , it's working perfectly ... but it's not working when emulate the app on the browser with  ionic serve

**Comment by obaqueiro** [comment]
Hi, I am what I think is a similar error. I followed the simple instructions  and get:

```Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'items' since it isn't a known property of 'select-searchable'.
1. If 'select-searchable' is an Angular component and it has 'items' input, then verify that it is part of this module.
```

Also, in VS Code (my editor of choice) I am getting the following warning:
```
[Angular]
'select-searchable' is not a known element:
1. If 'select-searchable' is an Angular component, then verify that it is part of this module.
2. If 'select-searchable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

**Comment by obaqueiro** [comment]
FWIW I get the same error when running the application directly in the device, via:
```
ionic cordova run android --device
```

**Comment by obaqueiro** [comment]
I think I found the issue (this made it work for me).  Ionic 3 adds a new file for each page that is created. The file is named ```page_name.module.ts```.  I added a reference to the SelectSearchableModule to that file and it made it work:

```
import { SelectSearchableModule } from 'ionic-select-searchable';
import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { AdminInformationPage } from './admin-information';

@NgModule({
  declarations: [
    AdminInformationPage,
  ],
  imports: [
    IonicPageModule.forChild(AdminInformationPage),
    SelectSearchableModule
  ],
})
export class AdminInformationPageModule {}
```

**Comment by sromero93** [comment]
Hi, 

I am having an issue as well. I updated the plugin to the newest version and now the searchable popup won't show when I click on the corresponding form field. The build works and I can run it fine on my device without any errors, but the plugin just doesn't respond.

**Comment by eakoriakin** [comment]
Try the latest [3.1.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/3.1.0) version.
```
npm i ionic-selectable@3.1.0
```

Then check out a live [demo on Stackblitz](https://stackblitz.com/edit/ionic-selectable-basic) to make sure your configuration is correct.

**Comment by mdparthi** [comment]
> 
> 
> I think I found the issue (this made it work for me). Ionic 3 adds a new file for each page that is created. The file is named `page_name.module.ts`. I added a reference to the SelectSearchableModule to that file and it made it work:
> 
> An example file:
> 
> ```
> import { SelectSearchableModule } from 'ionic-select-searchable';
> import { NgModule } from '@angular/core';
> import { IonicPageModule } from 'ionic-angular';
> import { AdminInformationPage } from './admin-information';
> 
> @NgModule({
>   declarations: [
>     AdminInformationPage,
>   ],
>   imports: [
>     IonicPageModule.forChild(AdminInformationPage),
>     SelectSearchableModule
>   ],
> })
> export class AdminInformationPageModule {}
> ```
> 
> Might be worth noting in the ReadMe file.

It really helped me to solve the issue faster

**Comment by zcazares** [comment]
I have the same issue with 4.4.0 version, i tried everything and it doesn´t work :(

**Comment by jbdioli** [comment]
Hello
Some one have the solution to make it works with ionic 4 ?

**Comment by Corrado2601** [comment]
Try this [https://www.npmjs.com/package/ionic-selectable](url) this works with ionic 4

**Comment by eakoriakin** [comment]
The issue is probably you don't import `IonicSelectableModule` correctly, it should be imported into each page module file:

https://github.com/eakoriakin/ionic-selectable#getting-started

**Note:** Additionally, if you use Ionic 3+ you might be as well using lazy loaded pages. Check if your pages have a module file, for example, `home.module.ts`, and if they do then import `IonicSelectableModule` to each page module too.

```
import { IonicSelectableModule } from 'ionic-selectable';
import { HomePage } from './home';

@NgModule({
  declarations: [
    HomePage
  ],
  imports: [
    IonicPageModule.forChild(HomePage),
    IonicSelectableModule
  ]
})
export class HomePageModule { }

**Comment by ritesh2496** [comment]
ERROR in node_modules/@ionic/core/dist/types/components.d.ts(5197,5): error TS2717: Subsequent property declarations must have the same type.  Property ''IonCard'' must be of type 'IonCard', but here has type 'IonCard'.
[ng] node_modules/@ionic/core/dist/types/components.d.ts(5217,5): error TS2717: Subsequent property declarations must have the same type.  Property ''IonItemSliding'' must be of type 'IonItemSliding', but here has type 'IonItemSliding'.
[ng] node_modules/@ionic/core/dist/types/components.d.ts(5245,5): error TS2717: Subsequent property declarations must have the same type.  Property ''IonRefresher'' must be of type 'IonRefresher', but here has type 'IonRefresher'.[ng] node_modules/@ionic/core/dist/types/components.d.ts(5254,5): error TS2717: Subsequent property declarations must have the same type.  Property ''IonSearchbar'' must be of type 'IonSearchbar', but here has type 'IonSearchbar'.[ng] node_modules/@ionic/core/dist/types/components.d.ts(5270,5): error TS2717: Subsequent property declarations must have the same type.  Property ''IonTextarea'' must be of type 'IonTextarea', but here has type 'IonTextarea'.
[ng] node_modules/@ionic/core/dist/types/components.d.ts(5297,5): error TS2717: Subsequent property declarations must have the same type.  Property ''ion-card'' must be of type 'IonCardAttributes', but here has type 'IonCardAttributes'.
[ng] node_modules/@ionic/core/dist/types/components.d.ts(5309,5): error TS2717: Subsequent property declarations must have the same type.  Property ''ion-img'' must be of type 'IonImgAttributes', but here has type 'IonImgAttributes'.
[ng] node_modules/@ionic/core/dist/types/components.d.ts(5345,5): error TS2717: Subsequent property declarations must have the same type.  Property ''ion-refresher'' must be of type 'IonRefresherAttributes', but here has type 'IonRefresherAttributes'.
[ng] node_modules/@ionic/core/dist/types/components.d.ts(5354,5): error TS2717: Subsequent property declarations must have the same type.  Property ''ion-searchbar'' must be of type 'IonSearchbarAttributes', but here has type 'IonSearchbarAttributes'.
[ng] node_modules/@ionic/core/dist/types/components.d.ts(5370,5): error TS2717: Subsequent property declarations must have the same type.  Property ''ion-textarea'' must be of type 'IonTextareaAttributes', but here has type 'IonTextareaAttributes'.
