### ISSUE TITLE
Additional button in header

### ISSUE THREAD

**Issue by aces-tm** [eakoriakin/ionic-selectable#89]
Is there a way to add a button in the header so it can be used for additional functions. For example, I'd like to give users option to create a new tag so I need an option on the selectable list to call alert or popup.

Currently there is only close button that can be customized.

Thanks

**Comment by aces-tm** [comment]
Sorry to bother, but any ideas when is this going to be available?

Just a suggestion... along with button to to create a new item it'd be great to be able to edit or delete item... Thanks for your work

**Comment by eakoriakin** [comment]
Hey @aces-tm, it's finally finished 🙂 
Try this demo:
https://stackblitz.com/edit/ionic-select-searchable-add-item?file=pages%2Fhome%2Fhome.ts

Version to use:
`npm i ionic-select-searchable@2.9.2`

**Comment by kodeine** [comment]
The links goes to a 404 page.


Yikes! The page you requested couldn't be found.
If you think this is a bug/problem on our end, please file an issue over at https://github.com/stackblitz/core

**Comment by eakoriakin** [comment]
Okay, seems like I need to correct the links...
Meanwhile, checkout the source code samples.

Editing:
https://github.com/eakoriakin/ionic-selectable/tree/master/src/app/pages/editing

Editing async:
https://github.com/eakoriakin/ionic-selectable/tree/master/src/app/pages/editing-async

Adding on search fail:
https://github.com/eakoriakin/ionic-selectable/tree/master/src/app/pages/adding-on-search-fail

Adding on search fail async:
https://github.com/eakoriakin/ionic-selectable/tree/master/src/app/pages/adding-on-search-fail-async

**Comment by kodeine** [comment]
Is that added?

**Comment by eakoriakin** [comment]
@kodeine hey, not yet, but I'll add it a bit later

**Comment by eakoriakin** [comment]
@kodeine here are updated links, you can find them in the docs as well now:

- [Editing](https://stackblitz.com/edit/ionic-selectable-editing?file=app/pages/home/home.html)
- [Editing async](https://stackblitz.com/edit/ionic-selectable-editing-async?file=app/pages/home/home.html)
- [Adding on search fail](https://stackblitz.com/edit/ionic-selectable-adding-on-search-fail?file=app/pages/home/home.html)
- [Adding on search fail async](https://stackblitz.com/edit/ionic-selectable-adding-on-search-fail-async?file=app/pages/home/home.html)
