### ISSUE TITLE
Help with angular/core versions

### ISSUE THREAD

**Issue by nazarenoc** [eakoriakin/ionic-selectable#92]
Hi, I'm trying to use this component with @angular/core version 3.6.0, but without success, because I receive that warning during npm install: 
"npm WARN ionic-select-searchable@2.9.0 requires a peer of @angular/core@>=4.1.3 but none is installed. You must install peer dependencies yourself."

So when I compile my app and test it on my device the component doesn't work properly. For example, when I use ion-label with floating directive the label did not go to left-top as expected.

I'll appreciate some help.

Thanks

Nazareno Costa

**Comment by eakoriakin** [comment]
Hey @nazarenoc sorry for a late response. Can you share a sample of your code?

**Comment by eakoriakin** [comment]
A new version is available - [3.1.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/3.1.0).
Maybe it will solve your issue.

```
npm i ionic-selectable@3.1.0
```

Also check out a live [demo on Stackblitz](https://stackblitz.com/edit/ionic-selectable-basic) to make sure your configuration is correct.
