### ISSUE TITLE
Problem with alignment

### ISSUE THREAD

**Issue by victorblq** [eakoriakin/ionic-selectable#95]
I need that the value text shows aligned to full left because my value is a little bit long (people names) and now it is cutting the value to put "...", how can I achieve this?

Here a screenshot of the NOT expected behaviour:
https://ibb.co/imTvOU

**Comment by eakoriakin** [comment]
Hey @victorblq, try to use `stacked` or `floating` `ion-label`, e.g.:
```
<ion-item>
  <ion-label position="stacked">Port</ion-label>
  <ionic-selectable #portComponent2 [(ngModel)]="portStacked"
    itemValueField="id" itemTextField="name" [items]="ports" [canClear]="true">
  </ionic-selectable>
</ion-item>
```

**Comment by victorblq** [comment]
I'm using the old version "select-searchable", but I'll update today to the new "ionic-selectable" and test this, many thanks!
