### ISSUE TITLE
No way to clear user-entered text?

### ISSUE THREAD

**Issue by alenl** [eakoriakin/ionic-selectable#96]
The `clear()` function resets the model and the currently selected item correctly and it looks "empty" (shows placeholder text), but when the user clicks on the component, the search box shows the old user-entered text instead of empty string as expected. Is there a way to clear it? The `searchText` property is read-only so can't use that.
The use case for this is reusing the same component to add items to a list. The empty component is at the end of the list and when the user types something into it and select a found item, the found item is added in front of the component and the component is cleared. This works well, aside from that it looks weird to click on empty component and get some old string pre-entered.
What do you think is a proper solution? Should `clear()` clear the text as well, or should there be another API to clear the text?

**Comment by alenl** [comment]
Note: seems that setting `component._searchText = "";` does the trick. I don't like using such an undocumented internal, though, in the long term. Please advise of a better approach, thanks!

**Comment by eakoriakin** [comment]
Hi @alenl, I'll have a look later

**Comment by dblohar** [comment]
Thank you this component.
I have same this issue.
Suggestion : `searchText`  value have to be clear when  click on clear button.

**Comment by eakoriakin** [comment]
Hey guys, it's now possible to set `searchText` in both [3.2.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/3.2.0) and [4.2.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/4.2.0) versions.

```
<ionic-selectable [canClear]="true" (onClear)="portClear($event)">
</ionic-selectable>
```

```
portClear(event: {
  component: IonicSelectableComponent,
  items: any[]
}) {
  event.component.searchText = '';
}
```
