### ISSUE TITLE
A feature request => event on each item selection when isMultiple is set to true.

### ISSUE THREAD

**Issue by lightyaer** [eakoriakin/ionic-selectable#97]
Thanks for this awesome tool, I couldn't believe its versatility after going through the documentation, Have been using it in production in 2 apps. Although, I have a feature request as follows,

I have about a 100,000 products in my db, When it comes to products, quantity is also associated to it..
So in case of [isMultiple] set to true, I wanted an event on each selection of product. 

There is change event, which is invoked when the user has selected all the products he wants to use. I need an event like onSelect where on selecting each product an event is emitted. 

If this feature/event already exists, kindly guide me through it. 
Thanks in Advance, 
Regards.

**Comment by eakoriakin** [comment]
Hey, sorry for a late reply, I was busy working on v4. There’s no such a feature now, but I’ll certainly add it soon.

Thanks for using the component :)

**Comment by eakoriakin** [comment]
Hey man, I've added [onSelect](https://github.com/eakoriakin/ionic-selectable/wiki/Documentation#onselect) event to both [3.2.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/3.2.0) and [4.2.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/4.2.0) versions. Enjoy 😄
