### ISSUE TITLE
Ionic 3 lazy loading error

### ISSUE THREAD

**Issue by teshtek** [eakoriakin/ionic-selectable#98]
I'm working on ionic 3, so lazy loading so this means only page has its module.ts. 
I imported evrything, no errors, but when i run, it gives me always the same error : 

> ERROR Error: Uncaught (in promise): Error: No component factory found for SelectSearchablePageComponent. Did you add it to @NgModule.entryComponents?(…)

This is the module:

```
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { NPage } from './n';
import { SelectSearchableModule } from 'ionic-select-searchable';
@NgModule({
  
  declarations: [
    NPage
  ],
  imports: [
    IonicPageModule.forChild(NPage),
    SelectSearchableModule
  ],
})
export class NPageModule {}
```

**Comment by eakoriakin** [comment]
Hey, sorry for a late reply. Can you share a code sample please,

**Comment by eakoriakin** [comment]
Hey guys, try the latest [3.1.0](https://github.com/eakoriakin/ionic-selectable/releases/tag/3.1.0) version.
```
npm i ionic-selectable@3.1.0
```

Then check out a live [demo on Stackblitz](https://stackblitz.com/edit/ionic-selectable-basic) to make sure your configuration is correct.
