### ISSUE TITLE
Question about search

### ISSUE THREAD

**Issue by Wcanizalez** [eakoriakin/ionic-selectable#99]
Hello, I would like to know in what way I can do to search in a list where I have: code and name, I would like to search by both fields, I remember that you had an example of that form but it seems that it is not available anymore.

Thanks.

**Comment by eakoriakin** [comment]
Hey @Wcanizalez, it's still available, have a look at this demo:
https://stackblitz.com/edit/ionic-selectable-on-search?file=pages/home/home.ts
